require('common');

local settings = T{ };
settings["Visible"] = T{ };
settings["SC"] = true;
settings["Melee"] = false;
settings["Ranged"] = false;
settings["COR_Rolls"] = false;
settings["Mob_TP"] = false;
settings["Visible_Length"] = 8;
settings["BRD_Buff"] = false;
settings["Timestamp"] = false;
settings["Pet_Melee"] = true;
settings["Pet_Command"] = false;
settings["WS_THRESHOLD"] = 600;
settings["MAX_THRESHOLD"] = 99999;
settings["Mob_Melee"] = false;
settings["Healing"] = true;
settings["Ability"] = true;
settings["Line_Height"] = 20;
settings["Mob_Death"] = true;
settings["Pet"] = true;
settings["Paging"] = false;
settings["Visible"][1] = true;
settings["Mob_Spell"] = false;
settings["Streaming"] = true;
settings["Enfeeble"] = true;
settings["WS"] = true;
settings["X"] = 100;
settings["Pet_TP"] = true;
settings["Pet_Heal"] = true;
settings["Y"] = 100;
settings["MAGIC_THRESHOLD"] = 1000;
settings["Magic"] = true;
settings["Deaths"] = false;

return settings;
