require('common');

local settings = T{ };
settings["window"] = T{ };
settings["window"]["backgroundColor"] = T{ };
settings["window"]["scale"] = T{ };
settings["window"]["textColor"] = T{ };
settings["window"]["borderColor"] = T{ };
settings["window"]["opacity"] = T{ };
settings["components"] = T{ };
settings["components"]["alwaysVisible"] = T{ };
settings["components"]["hideMap"] = T{ };
settings["components"]["petStayCounter"] = T{ };
settings["components"]["petTarget"] = T{ };
settings["components"]["petDuration"] = T{ };
settings["components"]["hideLog"] = T{ };
settings["components"]["petRecasts"] = T{ };
settings["components"]["petStats"] = T{ };
settings["components"]["petName"] = T{ };
settings["charmUntil"] = T{ };
settings["window"]["backgroundColor"][1] = 0;
settings["window"]["backgroundColor"][2] = 3.3617018890819139e-11;
settings["window"]["backgroundColor"][3] = 9.9999999747524271e-07;
settings["window"]["backgroundColor"][4] = 1;
settings["window"]["scale"][1] = 1;
settings["window"]["textColor"][1] = 1;
settings["window"]["textColor"][2] = 0.9999997615814209;
settings["window"]["textColor"][3] = 0.99998998641967773;
settings["window"]["textColor"][4] = 1;
settings["window"]["borderColor"][1] = 1;
settings["window"]["borderColor"][2] = 0.99998998641967773;
settings["window"]["borderColor"][3] = 0.99998998641967773;
settings["window"]["borderColor"][4] = 1;
settings["window"]["opacity"][1] = 1;
settings["components"]["alwaysVisible"][1] = false;
settings["components"]["hideMap"][1] = true;
settings["components"]["petStayCounter"][1] = true;
settings["components"]["petTarget"][1] = true;
settings["components"]["petDuration"][1] = true;
settings["components"]["hideLog"][1] = true;
settings["components"]["petRecasts"][1] = true;
settings["components"]["petStats"][1] = true;
settings["components"]["petName"][1] = true;
settings["charmUntil"][1] = 1767023514;

return settings;
