return T{
    Default = T{
        ["LTRT:7"] = {
            ActionType              = 'Item',
            Id                      = 4165,
            Macro                   = T{
                "/item \"Silent Oil\" <me>",
            },
            Label                   = "Silent Oil",
            Image                   = "ITEM:4165",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:1"] = {
            ActionType              = 'Spell',
            Id                      = 247,
            Macro                   = T{
                "/ma \"Aspir\" <t>",
            },
            Label                   = "Aspir",
            Image                   = "spells/247.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:1"] = {
            ActionType              = 'Spell',
            Id                      = 245,
            Macro                   = T{
                "/ma \"Drain\" <t>",
            },
            Label                   = "Drain",
            Image                   = "spells/245.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:4"] = {
            ActionType              = 'Command',
            Macro                   = T{
                "/tc palette change Light",
            },
            Label                   = "Light",
            Image                   = "misc/command.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:1"] = {
            ActionType              = 'Command',
            Macro                   = T{
                "/tc palette change Base",
            },
            Label                   = "Enfeeble",
            Image                   = "misc/command.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:3"] = {
            ActionType              = 'Spell',
            Id                      = 338,
            Macro                   = T{
                "/ma \"Utsusemi: Ichi\" <me>",
            },
            Label                   = "Utsusemi: Ichi",
            Image                   = "spells/338.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:2"] = {
            ActionType              = 'Command',
            Macro                   = T{
                "/tc palette change Darkness",
            },
            Label                   = "Darkness",
            Image                   = "misc/command.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:1"] = {
            ActionType              = 'Spell',
            Id                      = 338,
            Macro                   = T{
                "/ma \"Utsusemi: Ichi\" <me>",
            },
            Label                   = "Utsusemi: Ichi",
            Image                   = "spells/338.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:3"] = {
            ActionType              = 'Command',
            Macro                   = T{
                "/tc palette change Prebuff",
            },
            Label                   = "Prebuff",
            Image                   = "misc/command.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:8"] = {
            ActionType              = 'Spell',
            Id                      = 353,
            Macro                   = T{
                "/ma \"Tonko: Ichi\" <me>",
            },
            Label                   = "Tonko: Ichi",
            Image                   = "spells/353.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:1"] = {
            ActionType              = 'Spell',
            Id                      = 252,
            Macro                   = T{
                "/ma \"Stun\" <t>",
                "/p Stun <t> <scall21> Lojan next!",
            },
            Label                   = "Stun",
            Image                   = "spells/252.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 58,
                Macro                   = T{
                    "/ma \"Paralyze\" <t>",
                },
                Label                   = "Paralyze",
                Image                   = "spells/58.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Spell',
                Id                      = 273,
                Macro                   = T{
                    "/ma \"Sleepga\" <t>",
                },
                Label                   = "Sleepga",
                Image                   = "spells/273.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Spell',
                Id                      = 259,
                Macro                   = T{
                    "/ma \"Sleep II\" <t>",
                },
                Label                   = "Sleep II",
                Image                   = "spells/259.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/tc palette change Light",
                },
                Label                   = "Light",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Spell',
                Id                      = 274,
                Macro                   = T{
                    "/ma \"Sleepga II\" <t>",
                },
                Label                   = "Sleepga II",
                Image                   = "spells/274.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 23,
                Macro                   = T{
                    "/ma \"Dia\" <t>",
                },
                Label                   = "Dia",
                Image                   = "spells/23.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Spell',
                Id                      = 231,
                Macro                   = T{
                    "/ma \"Bio II\" <t>",
                },
                Label                   = "Bio II",
                Image                   = "spells/231.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Spell',
                Id                      = 258,
                Macro                   = T{
                    "/ma \"Bind\" <t>",
                },
                Label                   = "Bind",
                Image                   = "spells/258.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Spell',
                Id                      = 59,
                Macro                   = T{
                    "/ma \"Silence\" <t>",
                },
                Label                   = "Silence",
                Image                   = "spells/59.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Spell',
                Id                      = 221,
                Macro                   = T{
                    "/ma \"Poison II\" <t>",
                },
                Label                   = "Poison II",
                Image                   = "spells/221.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:8"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells/353.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 56,
                Macro                   = T{
                    "/ma \"Slow\" <t>",
                },
                Label                   = "Slow",
                Image                   = "spells/56.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Spell',
                Id                      = 253,
                Macro                   = T{
                    "/ma \"Sleep\" <t>",
                },
                Label                   = "Sleep",
                Image                   = "spells/253.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:3"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells/338.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 254,
                Macro                   = T{
                    "/ma \"Blind\" <t>",
                },
                Label                   = "Blind",
                Image                   = "spells/254.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:4"] = {
                ActionType              = 'Spell',
                Id                      = 260,
                Macro                   = T{
                    "/ma \"Dispel\" <t>",
                },
                Label                   = "Dispel",
                Image                   = "spells/260.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:1"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells/338.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 24,
                Macro                   = T{
                    "/ma \"Dia II\" <t>",
                },
                Label                   = "Dia II",
                Image                   = "spells/24.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 230,
                Macro                   = T{
                    "/ma \"Bio\" <t>",
                },
                Label                   = "Bio",
                Image                   = "spells/230.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 216,
                Macro                   = T{
                    "/ma \"Gravity\" <t>",
                },
                Label                   = "Gravity",
                Image                   = "spells/216.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Light", Bindings = T{
            ["RT2:7"] = {
                ActionType              = 'Spell',
                Id                      = 155,
                Macro                   = T{
                    "/ma \"Aero II\" <t>",
                },
                Label                   = "Aero II",
                Image                   = "spells/155.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Spell',
                Id                      = 175,
                Macro                   = T{
                    "/ma \"Firaga II\" <t>",
                },
                Label                   = "Firaga II",
                Image                   = "spells/175.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 154,
                Macro                   = T{
                    "/ma \"Aero\" <t>",
                },
                Label                   = "Aero",
                Image                   = "spells/154.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Spell',
                Id                      = 176,
                Macro                   = T{
                    "/ma \"Firaga III\" <t>",
                },
                Label                   = "Firaga III",
                Image                   = "spells/176.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 156,
                Macro                   = T{
                    "/ma \"Aero III\" <t>",
                },
                Label                   = "Aero III",
                Image                   = "spells/156.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Spell',
                Id                      = 166,
                Macro                   = T{
                    "/ma \"Thunder III\" <t>",
                },
                Label                   = "Thunder III",
                Image                   = "spells/166.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Spell',
                Id                      = 194,
                Macro                   = T{
                    "/ma \"Thundaga\" <t>",
                },
                Label                   = "Thundaga",
                Image                   = "spells/194.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 165,
                Macro                   = T{
                    "/ma \"Thunder II\" <t>",
                },
                Label                   = "Thunder II",
                Image                   = "spells/165.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:2"] = {
                ActionType              = 'Spell',
                Id                      = 184,
                Macro                   = T{
                    "/ma \"Aeroga\" <t>",
                },
                Label                   = "Aeroga",
                Image                   = "spells/184.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Spell',
                Id                      = 195,
                Macro                   = T{
                    "/ma \"Thundaga II\" <t>",
                },
                Label                   = "Thundaga II",
                Image                   = "spells/195.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:4"] = {
                ActionType              = 'Spell',
                Id                      = 237,
                Macro                   = T{
                    "/ma \"Choke\" <t>",
                },
                Label                   = "Choke",
                Image                   = "spells/237.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 167,
                Macro                   = T{
                    "/ma \"Thunder IV\" <t>",
                },
                Label                   = "Thunder IV",
                Image                   = "spells/167.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Spell',
                Id                      = 196,
                Macro                   = T{
                    "/ma \"Thundaga III\" <t>",
                },
                Label                   = "Thundaga III",
                Image                   = "spells/196.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:2"] = {
                ActionType              = 'Spell',
                Id                      = 239,
                Macro                   = T{
                    "/ma \"Shock\" <t>",
                },
                Label                   = "Shock",
                Image                   = "spells/239.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 144,
                Macro                   = T{
                    "/ma \"Fire\" <t>",
                },
                Label                   = "Fire",
                Image                   = "spells/144.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Spell',
                Id                      = 174,
                Macro                   = T{
                    "/ma \"Firaga\" <t>",
                },
                Label                   = "Firaga",
                Image                   = "spells/174.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:3"] = {
                ActionType              = 'Spell',
                Id                      = 235,
                Macro                   = T{
                    "/ma \"Burn\" <t>",
                },
                Label                   = "Burn",
                Image                   = "spells/235.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 145,
                Macro                   = T{
                    "/ma \"Fire II\" <t>",
                },
                Label                   = "Fire II",
                Image                   = "spells/145.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:3"] = {
                ActionType              = 'Spell',
                Id                      = 185,
                Macro                   = T{
                    "/ma \"Aeroga II\" <t>",
                },
                Label                   = "Aeroga II",
                Image                   = "spells/185.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 146,
                Macro                   = T{
                    "/ma \"Fire III\" <t>",
                },
                Label                   = "Fire III",
                Image                   = "spells/146.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:4"] = {
                ActionType              = 'Spell',
                Id                      = 186,
                Macro                   = T{
                    "/ma \"Aeroga III\" <t>",
                },
                Label                   = "Aeroga III",
                Image                   = "spells/186.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 157,
                Macro                   = T{
                    "/ma \"Aero IV\" <t>",
                },
                Label                   = "Aero IV",
                Image                   = "spells/157.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 164,
                Macro                   = T{
                    "/ma \"Thunder\" <t>",
                },
                Label                   = "Thunder",
                Image                   = "spells/164.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 212,
                Macro                   = T{
                    "/ma \"Burst\" <t>",
                },
                Label                   = "Burst",
                Image                   = "spells/212.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 147,
                Macro                   = T{
                    "/ma \"Fire IV\" <t>",
                },
                Label                   = "Fire IV",
                Image                   = "spells/147.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Darkness", Bindings = T{
            ["RT2:7"] = {
                ActionType              = 'Spell',
                Id                      = 160,
                Macro                   = T{
                    "/ma \"Stone II\" <t>",
                },
                Label                   = "Stone II",
                Image                   = "spells/160.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:4"] = {
                ActionType              = 'Spell',
                Id                      = 191,
                Macro                   = T{
                    "/ma \"Stonega III\" <t>",
                },
                Label                   = "Stonega III",
                Image                   = "spells/191.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 171,
                Macro                   = T{
                    "/ma \"Water III\" <t>",
                },
                Label                   = "Water III",
                Image                   = "spells/171.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Spell',
                Id                      = 201,
                Macro                   = T{
                    "/ma \"Waterga III\" <t>",
                },
                Label                   = "Waterga III",
                Image                   = "spells/201.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:2"] = {
                ActionType              = 'Spell',
                Id                      = 189,
                Macro                   = T{
                    "/ma \"Stonega\" <t>",
                },
                Label                   = "Stonega",
                Image                   = "spells/189.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Spell',
                Id                      = 179,
                Macro                   = T{
                    "/ma \"Blizzaga\" <t>",
                },
                Label                   = "Blizzaga",
                Image                   = "spells/179.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 149,
                Macro                   = T{
                    "/ma \"Blizzard\" <t>",
                },
                Label                   = "Blizzard",
                Image                   = "spells/149.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Spell',
                Id                      = 151,
                Macro                   = T{
                    "/ma \"Blizzard III\" <t>",
                },
                Label                   = "Blizzard III",
                Image                   = "spells/151.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:2"] = {
                ActionType              = 'Spell',
                Id                      = 236,
                Macro                   = T{
                    "/ma \"Frost\" <t>",
                },
                Label                   = "Frost",
                Image                   = "spells/236.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Spell',
                Id                      = 181,
                Macro                   = T{
                    "/ma \"Blizzaga III\" <t>",
                },
                Label                   = "Blizzaga III",
                Image                   = "spells/181.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 150,
                Macro                   = T{
                    "/ma \"Blizzard II\" <t>",
                },
                Label                   = "Blizzard II",
                Image                   = "spells/150.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Spell',
                Id                      = 180,
                Macro                   = T{
                    "/ma \"Blizzaga II\" <t>",
                },
                Label                   = "Blizzaga II",
                Image                   = "spells/180.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:4"] = {
                ActionType              = 'Spell',
                Id                      = 238,
                Macro                   = T{
                    "/ma \"Rasp\" <t>",
                },
                Label                   = "Rasp",
                Image                   = "spells/238.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 152,
                Macro                   = T{
                    "/ma \"Blizzard IV\" <t>",
                },
                Label                   = "Blizzard IV",
                Image                   = "spells/152.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:1"] = {
                ActionType              = 'Spell',
                Id                      = 247,
                Macro                   = T{
                    "/ma \"Aspir\" <t>",
                },
                Label                   = "Aspir",
                Image                   = "spells/247.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 169,
                Macro                   = T{
                    "/ma \"Water\" <t>",
                },
                Label                   = "Water",
                Image                   = "spells/169.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 206,
                Macro                   = T{
                    "/ma \"Freeze\" <t>",
                },
                Label                   = "Freeze",
                Image                   = "spells/206.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Spell',
                Id                      = 199,
                Macro                   = T{
                    "/ma \"Waterga\" <t>",
                },
                Label                   = "Waterga",
                Image                   = "spells/199.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:3"] = {
                ActionType              = 'Spell',
                Id                      = 240,
                Macro                   = T{
                    "/ma \"Drown\" <t>",
                },
                Label                   = "Drown",
                Image                   = "spells/240.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:3"] = {
                ActionType              = 'Spell',
                Id                      = 190,
                Macro                   = T{
                    "/ma \"Stonega II\" <t>",
                },
                Label                   = "Stonega II",
                Image                   = "spells/190.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 210,
                Macro                   = T{
                    "/ma \"Quake\" <t>",
                },
                Label                   = "Quake",
                Image                   = "spells/210.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 161,
                Macro                   = T{
                    "/ma \"Stone III\" <t>",
                },
                Label                   = "Stone III",
                Image                   = "spells/161.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 170,
                Macro                   = T{
                    "/ma \"Water II\" <t>",
                },
                Label                   = "Water II",
                Image                   = "spells/170.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 162,
                Macro                   = T{
                    "/ma \"Stone IV\" <t>",
                },
                Label                   = "Stone IV",
                Image                   = "spells/162.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Spell',
                Id                      = 200,
                Macro                   = T{
                    "/ma \"Waterga II\" <t>",
                },
                Label                   = "Waterga II",
                Image                   = "spells/200.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 159,
                Macro                   = T{
                    "/ma \"Stone\" <t>",
                },
                Label                   = "Stone",
                Image                   = "spells/159.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 172,
                Macro                   = T{
                    "/ma \"Water IV\" <t>",
                },
                Label                   = "Water IV",
                Image                   = "spells/172.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Prebuff", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 106,
                Macro                   = T{
                    "/ma \"Phalanx\" <me>",
                },
                Label                   = "Phalanx",
                Image                   = "spells/106.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Spell',
                Id                      = 137,
                Macro                   = T{
                    "/ma \"Sneak\" <t>",
                },
                Label                   = "Sneak",
                Image                   = "spells/137.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Spell',
                Id                      = 2,
                Macro                   = T{
                    "/ma \"Cure II\" <t>",
                },
                Label                   = "Cure II",
                Image                   = "spells/2.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 49,
                Macro                   = T{
                    "/ma \"Shell II\" <t>",
                },
                Label                   = "Shell II",
                Image                   = "spells/49.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 54,
                Macro                   = T{
                    "/ma \"Stoneskin\" <me>",
                },
                Label                   = "Stoneskin",
                Image                   = "spells/54.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 55,
                Macro                   = T{
                    "/ma \"Aquaveil\" <me>",
                },
                Label                   = "Aquaveil",
                Image                   = "spells/55.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 126,
                Macro                   = T{
                    "/ma \"Protectra II\" <me>",
                },
                Label                   = "Protectra II",
                Image                   = "spells/126.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Spell',
                Id                      = 136,
                Macro                   = T{
                    "/ma \"Invisible\" <t>",
                },
                Label                   = "Invisible",
                Image                   = "spells/136.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 12,
                Macro                   = T{
                    "/ma \"Raise\" <t>",
                },
                Label                   = "Raise",
                Image                   = "spells/12.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Spell',
                Id                      = 1,
                Macro                   = T{
                    "/ma \"Cure\" <t>",
                },
                Label                   = "Cure",
                Image                   = "spells/1.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 44,
                Macro                   = T{
                    "/ma \"Protect II\" <t>",
                },
                Label                   = "Protect II",
                Image                   = "spells/44.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Spell',
                Id                      = 131,
                Macro                   = T{
                    "/ma \"Shellra II\" <me>",
                },
                Label                   = "Shellra II",
                Image                   = "spells/131.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:2"] = {
                ActionType              = 'Spell',
                Id                      = 135,
                Macro                   = T{
                    "/ma \"Reraise\" <me>",
                },
                Label                   = "Reraise",
                Image                   = "spells/135.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Spell',
                Id                      = 3,
                Macro                   = T{
                    "/ma \"Cure III\" <t>",
                },
                Label                   = "Cure III",
                Image                   = "spells/3.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 53,
                Macro                   = T{
                    "/ma \"Blink\" <me>",
                },
                Label                   = "Blink",
                Image                   = "spells/53.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};