return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["RT2:7"] = {
                ActionType              = 'Spell',
                Id                      = 136,
                Macro                   = T{
                    "/ma \"Invisible\" <t>",
                },
                Label                   = "Invisible",
                Image                   = "spells/136.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 574,
                Macro                   = T{
                    "/ja \"Third Eye\" <me>",
                },
                Label                   = "Third Eye",
                Image                   = "abilities/62.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Ability',
                Id                      = 575,
                Macro                   = T{
                    "/ja \"Meditate\" <me>",
                },
                Label                   = "Meditate",
                Image                   = "abilities/63.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 117,
                Macro                   = T{
                    "/ws \"Vorpal Thrust\" <t>",
                },
                Label                   = "Vorpal Thrust",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Ability',
                Id                      = 580,
                Macro                   = T{
                    "/ja \"Super Jump\" <t>",
                },
                Label                   = "Super Jump",
                Image                   = "abilities/68.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 119,
                Macro                   = T{
                    "/ws \"Wheeling Thrust\" <t>",
                },
                Label                   = "Wheeling Thrust",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 48,
                Macro                   = T{
                    "/ma \"Shell\" <t>",
                },
                Label                   = "Shell",
                Image                   = "spells/48.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 578,
                Macro                   = T{
                    "/ja \"Jump\" <t>",
                },
                Label                   = "Jump",
                Image                   = "abilities/66.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 55,
                Macro                   = T{
                    "/ma \"Aquaveil\" <me>",
                },
                Label                   = "Aquaveil",
                Image                   = "spells/55.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 114,
                Macro                   = T{
                    "/ws \"Raiden Thrust\" <t>",
                },
                Label                   = "Raiden Thrust",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:7"] = {
                ActionType              = 'Spell',
                Id                      = 54,
                Macro                   = T{
                    "/ma \"Stoneskin\" <me>",
                },
                Label                   = "Stoneskin",
                Image                   = "spells/54.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 579,
                Macro                   = T{
                    "/ja \"High Jump\" <t>",
                },
                Label                   = "High Jump",
                Image                   = "abilities/67.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 115,
                Macro                   = T{
                    "/ws \"Leg Sweep\" <t>",
                },
                Label                   = "Leg Sweep",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:5"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells/353.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Weaponskill',
                Id                      = 118,
                Macro                   = T{
                    "/ws \"Skewer\" <t>",
                },
                Label                   = "Skewer",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 137,
                Macro                   = T{
                    "/ma \"Sneak\" <t>",
                },
                Label                   = "Sneak",
                Image                   = "spells/137.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 23,
                Macro                   = T{
                    "/ma \"Dia\" <t>",
                },
                Label                   = "Dia",
                Image                   = "spells/23.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:1"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells/338.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 220,
                Macro                   = T{
                    "/ma \"Poison\" <t>",
                },
                Label                   = "Poison",
                Image                   = "spells/220.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 592,
                Macro                   = T{
                    "/ja \"Spirit Link\" <me>",
                },
                Label                   = "Spirit Link",
                Image                   = "abilities/80.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 573,
                Macro                   = T{
                    "/ja \"Call Wyvern\" <me>",
                },
                Label                   = "Call Wyvern",
                Image                   = "abilities/61.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 585,
                Macro                   = T{
                    "/ja \"Stay\" <me>",
                },
                Label                   = "Stay",
                Image                   = "abilities/73.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 807,
                Macro                   = T{
                    "/ja \"Steady Wing\" <me>",
                },
                Label                   = "Steady Wing",
                Image                   = "abilities/295.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 112,
                Macro                   = T{
                    "/ws \"Double Thrust\" <t>",
                },
                Label                   = "Double Thrust",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:1"] = {
                ActionType              = 'Item',
                Id                      = 4558,
                Macro                   = T{
                    "/item \"Yagudo Drink\" <me>",
                },
                Label                   = "Yagudo Drink",
                Image                   = "ITEM:4558",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 71,
                Macro                   = T{
                    "/ma \"Barwatera\" <me>",
                },
                Label                   = "Barwatera",
                Image                   = "spells/71.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 53,
                Macro                   = T{
                    "/ma \"Blink\" <me>",
                },
                Label                   = "Blink",
                Image                   = "spells/53.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:6"] = {
                ActionType              = 'Ability',
                Id                      = 543,
                Macro                   = T{
                    "/ja \"Berserk\" <me>",
                },
                Label                   = "Berserk",
                Image                   = "abilities/31.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Ability',
                Id                      = 685,
                Macro                   = T{
                    "/ja \"Hasso\" <me>",
                },
                Label                   = "Hasso",
                Image                   = "abilities/173.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 120,
                Macro                   = T{
                    "/ws \"Impulse Drive\" <t>",
                },
                Label                   = "Impulse Drive",
                Image                   = "ITEM:21883",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Ability',
                Id                      = 807,
                Macro                   = T{
                    "/ja \"Steady Wing\" <me>",
                },
                Label                   = "Steady Wing",
                Image                   = "abilities/295.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:4"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities/52.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 106,
                Macro                   = T{
                    "/ma \"Phalanx\" <me>",
                },
                Label                   = "Phalanx",
                Image                   = "spells/106.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 44,
                Macro                   = T{
                    "/ma \"Protect II\" <t>",
                },
                Label                   = "Protect II",
                Image                   = "spells/44.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 116,
                Macro                   = T{
                    "/ws \"Penta Thrust\" <t>",
                },
                Label                   = "Penta Thrust",
                Image                   = "ITEM:16885",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Spell',
                Id                      = 101,
                Macro                   = T{
                    "/ma \"Enblizzard\" <me>",
                },
                Label                   = "Enblizzard",
                Image                   = "spells/101.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Ability',
                Id                      = 686,
                Macro                   = T{
                    "/ja \"Seigan\" <me>",
                },
                Label                   = "Seigan",
                Image                   = "abilities/174.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};