return T{
    Default = T{
        ["RT2:7"] = {
            ActionType              = 'Spell',
            Id                      = 267,
            Macro                   = T{
                "/ma \"Absorb-DEX\" <t>",
            },
            Label                   = "Absorb-DEX",
            Image                   = "spells/267.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:1"] = {
            ActionType              = 'Ability',
            Id                      = 589,
            Macro                   = T{
                "/ja \"Weapon Bash\" <t>",
            },
            Label                   = "Weapon Bash",
            Image                   = "abilities/77.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:3"] = {
            ActionType              = 'Ability',
            Id                      = 574,
            Macro                   = T{
                "/ja \"Third Eye\" <me>",
            },
            Label                   = "Third Eye",
            Image                   = "abilities/62.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:5"] = {
            ActionType              = 'Spell',
            Id                      = 354,
            Macro                   = T{
                "/ma \"Tonko: Ni\" <me>",
            },
            Label                   = "Tonko: Ni",
            Image                   = "spells/354.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:6"] = {
            ActionType              = 'Spell',
            Id                      = 269,
            Macro                   = T{
                "/ma \"Absorb-AGI\" <t>",
            },
            Label                   = "Absorb-AGI",
            Image                   = "spells/269.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:3"] = {
            ActionType              = 'Ability',
            Id                      = 556,
            Macro                   = T{
                "/ja \"Sneak Attack\" <me>",
            },
            Label                   = "Sneak Attack",
            Image                   = "abilities/44.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:4"] = {
            ActionType              = 'Ability',
            Id                      = 686,
            Macro                   = T{
                "/ja \"Seigan\" <me>",
            },
            Label                   = "Seigan",
            Image                   = "abilities/174.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:1"] = {
            ActionType              = 'Ability',
            Id                      = 588,
            Macro                   = T{
                "/ja \"Trick Attack\" <me>",
            },
            Label                   = "Trick Attack",
            Image                   = "abilities/76.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:2"] = {
            ActionType              = 'Ability',
            Id                      = 562,
            Macro                   = T{
                "/ja \"Arcane Circle\" <me>",
            },
            Label                   = "Arcane Circle",
            Image                   = "abilities/50.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:6"] = {
            ActionType              = 'Spell',
            Id                      = 230,
            Macro                   = T{
                "/ma \"Bio\" <t>",
            },
            Label                   = "Bio",
            Image                   = "spells/230.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:1"] = {
            ActionType              = 'Spell',
            Id                      = 338,
            Macro                   = T{
                "/ma \"Utsusemi: Ichi\" <me>",
            },
            Label                   = "Utsusemi: Ichi",
            Image                   = "spells/338.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:2"] = {
            ActionType              = 'Ability',
            Id                      = 582,
            Macro                   = T{
                "/ja \"Heel\" <me>",
            },
            Label                   = "Heel",
            Image                   = "abilities/70.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:7"] = {
            ActionType              = 'Spell',
            Id                      = 231,
            Macro                   = T{
                "/ma \"Bio II\" <t>",
            },
            Label                   = "Bio II",
            Image                   = "spells/231.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:1"] = {
            ActionType              = 'Spell',
            Id                      = 252,
            Macro                   = T{
                "/ma \"Stun\" <t>",
            },
            Label                   = "Stun",
            Image                   = "spells/252.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:7"] = {
            ActionType              = 'Ability',
            Id                      = 561,
            Macro                   = T{
                "/ja \"Souleater\" <me>",
            },
            Label                   = "Souleater",
            Image                   = "abilities/49.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:3"] = {
            ActionType              = 'Ability',
            Id                      = 585,
            Macro                   = T{
                "/ja \"Stay\" <me>",
            },
            Label                   = "Stay",
            Image                   = "abilities/73.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:8"] = {
            ActionType              = 'Ability',
            Id                      = 575,
            Macro                   = T{
                "/ja \"Meditate\" <me>",
            },
            Label                   = "Meditate",
            Image                   = "abilities/63.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:8"] = {
            ActionType              = 'Ability',
            Id                      = 583,
            Macro                   = T{
                "/ja \"Leave\" <me>",
            },
            Label                   = "Leave",
            Image                   = "abilities/71.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:4"] = {
            ActionType              = 'Ability',
            Id                      = 581,
            Macro                   = T{
                "/ja \"Fight\" <t>",
            },
            Label                   = "Fight",
            Image                   = "abilities/69.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:6"] = {
            ActionType              = 'Ability',
            Id                      = 584,
            Macro                   = T{
                "/ja \"Sic\" <me>",
            },
            Label                   = "Sic",
            Image                   = "abilities/72.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:6"] = {
            ActionType              = 'Ability',
            Id                      = 563,
            Macro                   = T{
                "/ja \"Last Resort\" <me>",
            },
            Label                   = "Last Resort",
            Image                   = "abilities/51.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:2"] = {
            ActionType              = 'Ability',
            Id                      = 685,
            Macro                   = T{
                "/ja \"Hasso\" <me>",
            },
            Label                   = "Hasso",
            Image                   = "abilities/173.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:5"] = {
            ActionType              = 'Spell',
            Id                      = 245,
            Macro                   = T{
                "/ma \"Drain\" <t>",
            },
            Label                   = "Drain",
            Image                   = "spells/245.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:3"] = {
            ActionType              = 'Spell',
            Id                      = 266,
            Macro                   = T{
                "/ma \"Absorb-STR\" <t>",
            },
            Label                   = "Absorb-STR",
            Image                   = "spells/266.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:4"] = {
            ActionType              = 'Ability',
            Id                      = 564,
            Macro                   = T{
                "/ja \"Charm\" <t>",
            },
            Label                   = "Charm",
            Image                   = "abilities/52.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:3"] = {
            ActionType              = 'Spell',
            Id                      = 339,
            Macro                   = T{
                "/ma \"Utsusemi: Ni\" <me>",
            },
            Label                   = "Utsusemi: Ni",
            Image                   = "spells/339.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:5"] = {
            ActionType              = 'Spell',
            Id                      = 271,
            Macro                   = T{
                "/ma \"Absorb-MND\" <t>",
            },
            Label                   = "Absorb-MND",
            Image                   = "spells/271.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:2"] = {
            ActionType              = 'Spell',
            Id                      = 268,
            Macro                   = T{
                "/ma \"Absorb-VIT\" <t>",
            },
            Label                   = "Absorb-VIT",
            Image                   = "spells/268.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:8"] = {
            ActionType              = 'Spell',
            Id                      = 270,
            Macro                   = T{
                "/ma \"Absorb-INT\" <t>",
            },
            Label                   = "Absorb-INT",
            Image                   = "spells/270.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:5"] = {
            ActionType              = 'Spell',
            Id                      = 247,
            Macro                   = T{
                "/ma \"Aspir\" <t>",
            },
            Label                   = "Aspir",
            Image                   = "spells/247.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["RT2:7"] = {
                ActionType              = 'Spell',
                Id                      = 267,
                Macro                   = T{
                    "/ma \"Absorb-DEX\" <t>",
                },
                Label                   = "Absorb-DEX",
                Image                   = "spells/267.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 589,
                Macro                   = T{
                    "/ja \"Weapon Bash\" <t>",
                },
                Label                   = "Weapon Bash",
                Image                   = "abilities/77.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Ability',
                Id                      = 574,
                Macro                   = T{
                    "/ja \"Third Eye\" <me>",
                },
                Label                   = "Third Eye",
                Image                   = "abilities/62.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 53,
                Macro                   = T{
                    "/ws \"Crescent Moon\" <t>",
                },
                Label                   = "Crescent Moon",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 269,
                Macro                   = T{
                    "/ma \"Absorb-AGI\" <t>",
                },
                Label                   = "Absorb-AGI",
                Image                   = "spells/269.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Ability',
                Id                      = 686,
                Macro                   = T{
                    "/ja \"Seigan\" <me>",
                },
                Label                   = "Seigan",
                Image                   = "abilities/174.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 270,
                Macro                   = T{
                    "/ma \"Absorb-INT\" <t>",
                },
                Label                   = "Absorb-INT",
                Image                   = "spells/270.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 258,
                Macro                   = T{
                    "/ma \"Bind\" <t>",
                },
                Label                   = "Bind",
                Image                   = "spells/258.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:3"] = {
                ActionType              = 'Spell',
                Id                      = 266,
                Macro                   = T{
                    "/ma \"Absorb-STR\" <t>",
                },
                Label                   = "Absorb-STR",
                Image                   = "spells/266.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 50,
                Macro                   = T{
                    "/ws \"Frostbite\" <t>",
                },
                Label                   = "Frostbite",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 247,
                Macro                   = T{
                    "/ma \"Aspir\" <t>",
                },
                Label                   = "Aspir",
                Image                   = "spells/247.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 253,
                Macro                   = T{
                    "/ma \"Sleep\" <t>",
                },
                Label                   = "Sleep",
                Image                   = "spells/253.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 51,
                Macro                   = T{
                    "/ws \"Freezebite\" <t>",
                },
                Label                   = "Freezebite",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:5"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells/353.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Weaponskill',
                Id                      = 54,
                Macro                   = T{
                    "/ws \"Sickle Moon\" <t>",
                },
                Label                   = "Sickle Moon",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities/69.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 230,
                Macro                   = T{
                    "/ma \"Bio\" <t>",
                },
                Label                   = "Bio",
                Image                   = "spells/230.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 575,
                Macro                   = T{
                    "/ja \"Meditate\" <me>",
                },
                Label                   = "Meditate",
                Image                   = "abilities/63.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 245,
                Macro                   = T{
                    "/ma \"Drain\" <t>",
                },
                Label                   = "Drain",
                Image                   = "spells/245.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 231,
                Macro                   = T{
                    "/ma \"Bio II\" <t>",
                },
                Label                   = "Bio II",
                Image                   = "spells/231.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Spell',
                Id                      = 252,
                Macro                   = T{
                    "/ma \"Stun\" <t>",
                },
                Label                   = "Stun",
                Image                   = "spells/252.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:7"] = {
                ActionType              = 'Ability',
                Id                      = 561,
                Macro                   = T{
                    "/ja \"Souleater\" <me>",
                },
                Label                   = "Souleater",
                Image                   = "abilities/49.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 55,
                Macro                   = T{
                    "/ws \"Spinning Slash\" <t>",
                },
                Label                   = "Spinning Slash",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 48,
                Macro                   = T{
                    "/ws \"Hard Slash\" <t>",
                },
                Label                   = "Hard Slash",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:8"] = {
                ActionType              = 'Ability',
                Id                      = 584,
                Macro                   = T{
                    "/ja \"Sic\" <me>",
                },
                Label                   = "Sic",
                Image                   = "abilities/72.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 52,
                Macro                   = T{
                    "/ws \"Shockwave\" <t>",
                },
                Label                   = "Shockwave",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 49,
                Macro                   = T{
                    "/ws \"Power Slash\" <t>",
                },
                Label                   = "Power Slash",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:6"] = {
                ActionType              = 'Ability',
                Id                      = 563,
                Macro                   = T{
                    "/ja \"Last Resort\" <me>",
                },
                Label                   = "Last Resort",
                Image                   = "abilities/51.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Ability',
                Id                      = 685,
                Macro                   = T{
                    "/ja \"Hasso\" <me>",
                },
                Label                   = "Hasso",
                Image                   = "abilities/173.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:2"] = {
                ActionType              = 'Spell',
                Id                      = 268,
                Macro                   = T{
                    "/ma \"Absorb-VIT\" <t>",
                },
                Label                   = "Absorb-VIT",
                Image                   = "spells/268.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:3"] = {
                ActionType              = 'Spell',
                Id                      = 339,
                Macro                   = T{
                    "/ma \"Utsusemi: Ni\" <me>",
                },
                Label                   = "Utsusemi: Ni",
                Image                   = "spells/339.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:4"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities/52.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:2"] = {
                ActionType              = 'Ability',
                Id                      = 562,
                Macro                   = T{
                    "/ja \"Arcane Circle\" <me>",
                },
                Label                   = "Arcane Circle",
                Image                   = "abilities/50.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 271,
                Macro                   = T{
                    "/ma \"Absorb-MND\" <t>",
                },
                Label                   = "Absorb-MND",
                Image                   = "spells/271.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:1"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells/338.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 585,
                Macro                   = T{
                    "/ja \"Stay\" <me>",
                },
                Label                   = "Stay",
                Image                   = "abilities/73.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 259,
                Macro                   = T{
                    "/ma \"Sleep II\" <t>",
                },
                Label                   = "Sleep II",
                Image                   = "spells/259.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="GAXE", Bindings = T{
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 80,
                Macro                   = T{
                    "/ws \"Shield Break\" <t>",
                },
                Label                   = "Shield Break",
                Image                   = "ITEM:18206",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 83,
                Macro                   = T{
                    "/ws \"Armor Break\" <t>",
                },
                Label                   = "Armor Break",
                Image                   = "ITEM:18206",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 81,
                Macro                   = T{
                    "/ws \"Iron Tempest\" <t>",
                },
                Label                   = "Iron Tempest",
                Image                   = "ITEM:18206",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 85,
                Macro                   = T{
                    "/ws \"Weapon Break\" <t>",
                },
                Label                   = "Weapon Break",
                Image                   = "ITEM:18206",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 82,
                Macro                   = T{
                    "/ws \"Sturmwind\" <t>",
                },
                Label                   = "Sturmwind",
                Image                   = "ITEM:18206",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 84,
                Macro                   = T{
                    "/ws \"Keen Edge\" <t>",
                },
                Label                   = "Keen Edge",
                Image                   = "ITEM:18206",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="scythe", Bindings = T{
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 96,
                Macro                   = T{
                    "/ws \"Slice\" <t>",
                },
                Label                   = "Slice",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 99,
                Macro                   = T{
                    "/ws \"Nightmare Scythe\" <t>",
                },
                Label                   = "Nightmare Scythe",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 101,
                Macro                   = T{
                    "/ws \"Vorpal Scythe\" <t>",
                },
                Label                   = "Vorpal Scythe",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 584,
                Macro                   = T{
                    "/ja \"Sic\" <me>",
                },
                Label                   = "Sic",
                Image                   = "abilities/72.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Weaponskill',
                Id                      = 102,
                Macro                   = T{
                    "/ws \"Guillotine\" <t>",
                },
                Label                   = "Guillotine",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:3"] = {
                ActionType              = 'Ability',
                Id                      = 556,
                Macro                   = T{
                    "/ja \"Sneak Attack\" <me>",
                },
                Label                   = "Sneak Attack",
                Image                   = "abilities/44.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 103,
                Macro                   = T{
                    "/ws \"Cross Reaper\" <t>",
                },
                Label                   = "Cross Reaper",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 100,
                Macro                   = T{
                    "/ws \"Spinning Scythe\" <t>",
                },
                Label                   = "Spinning Scythe",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 104,
                Macro                   = T{
                    "/ws \"Spiral Hell\" <t>",
                },
                Label                   = "Spiral Hell",
                Image                   = "ITEM:21830",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 98,
                Macro                   = T{
                    "/ws \"Shadow of Death\" <t>",
                },
                Label                   = "Shadow of Death",
                Image                   = "ITEM:16777",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:1"] = {
                ActionType              = 'Ability',
                Id                      = 588,
                Macro                   = T{
                    "/ja \"Trick Attack\" <me>",
                },
                Label                   = "Trick Attack",
                Image                   = "abilities/76.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="axe", Bindings = T{
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 64,
                Macro                   = T{
                    "/ws \"Raging Axe\" <t>",
                },
                Label                   = "Raging Axe",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 67,
                Macro                   = T{
                    "/ws \"Avalanche Axe\" <t>",
                },
                Label                   = "Avalanche Axe",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 65,
                Macro                   = T{
                    "/ws \"Smash Axe\" <t>",
                },
                Label                   = "Smash Axe",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 69,
                Macro                   = T{
                    "/ws \"Rampage\" <t>",
                },
                Label                   = "Rampage",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 66,
                Macro                   = T{
                    "/ws \"Gale Axe\" <t>",
                },
                Label                   = "Gale Axe",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 68,
                Macro                   = T{
                    "/ws \"Spinning Axe\" <t>",
                },
                Label                   = "Spinning Axe",
                Image                   = "ITEM:17928",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};