return T{
    Default = T{
        ["LT:7"] = {
            ActionType              = 'Spell',
            Id                      = 344,
            Macro                   = T{
                "/ma \"Hojo: Ichi\" <t>",
            },
            Label                   = "Hojo: Ichi",
            Image                   = "spells/344.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:4"] = {
            ActionType              = 'Spell',
            Id                      = 353,
            Macro                   = T{
                "/ma \"Tonko: Ichi\" <me>",
            },
            Label                   = "Tonko: Ichi",
            Image                   = "spells/353.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:3"] = {
            ActionType              = 'Spell',
            Id                      = 350,
            Macro                   = T{
                "/ma \"Dokumori: Ichi\" <t>",
            },
            Label                   = "Dokumori: Ichi",
            Image                   = "spells/350.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:6"] = {
            ActionType              = 'Spell',
            Id                      = 347,
            Macro                   = T{
                "/ma \"Kurayami: Ichi\" <t>",
            },
            Label                   = "Kurayami: Ichi",
            Image                   = "spells/347.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:8"] = {
            ActionType              = 'Spell',
            Id                      = 341,
            Macro                   = T{
                "/ma \"Jubaku: Ichi\" <t>",
            },
            Label                   = "Jubaku: Ichi",
            Image                   = "spells/341.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:2"] = {
            ActionType              = 'Item',
            Id                      = 4165,
            Macro                   = T{
                "/item \"Silent Oil\" <me>",
            },
            Label                   = "Silent Oil",
            Image                   = "ITEM:4165",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:6"] = {
            ActionType              = 'Weaponskill',
            Id                      = 128,
            Macro                   = T{
                "/ws \"Blade: Rin\" <t>",
            },
            Label                   = "Blade: Rin",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:8"] = {
            ActionType              = 'Weaponskill',
            Id                      = 130,
            Macro                   = T{
                "/ws \"Blade: Teki\" <t>",
            },
            Label                   = "Blade: Teki",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:5"] = {
            ActionType              = 'Weaponskill',
            Id                      = 131,
            Macro                   = T{
                "/ws \"Blade: To\" <t>",
            },
            Label                   = "Blade: To",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:7"] = {
            ActionType              = 'Weaponskill',
            Id                      = 129,
            Macro                   = T{
                "/ws \"Blade: Retsu\" <t>",
            },
            Label                   = "Blade: Retsu",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:1"] = {
            ActionType              = 'Spell',
            Id                      = 338,
            Macro                   = T{
                "/ma \"Utsusemi: Ichi\" <me>",
            },
            Label                   = "Utsusemi: Ichi",
            Image                   = "spells/338.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
    },
    Palettes = T{
        { Name="Base", Bindings = T{
        } },
    },
};