return T{
    Default = T{
        ["RT2:7"] = {
            ActionType              = 'Ability',
            Id                      = 582,
            Macro                   = T{
                "/ja \"Heel\" <me>",
            },
            Label                   = "Heel",
            Image                   = "abilities/70.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:1"] = {
            ActionType              = 'Spell',
            Id                      = 350,
            Macro                   = T{
                "/ma \"Dokumori: Ichi\" <t>",
            },
            Label                   = "Dokumori: Ichi",
            Image                   = "spells/350.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:3"] = {
            ActionType              = 'Spell',
            Id                      = 323,
            Macro                   = T{
                "/ma \"Hyoton: Ichi\" <t>",
            },
            Label                   = "Hyoton: Ichi",
            Image                   = "spells/323.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:3"] = {
            ActionType              = 'Weaponskill',
            Id                      = 133,
            Macro                   = T{
                "/ws \"Blade: Ei\" <t>",
            },
            Label                   = "Blade: Ei",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:6"] = {
            ActionType              = 'Ability',
            Id                      = 581,
            Macro                   = T{
                "/ja \"Fight\" <t>",
            },
            Label                   = "Fight",
            Image                   = "abilities/69.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:1"] = {
            ActionType              = 'Weaponskill',
            Id                      = 135,
            Macro                   = T{
                "/ws \"Blade: Ten\" <t>",
            },
            Label                   = "Blade: Ten",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:8"] = {
            ActionType              = 'Ability',
            Id                      = 585,
            Macro                   = T{
                "/ja \"Stay\" <me>",
            },
            Label                   = "Stay",
            Image                   = "abilities/73.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:2"] = {
            ActionType              = 'Item',
            Id                      = 4165,
            Macro                   = T{
                "/item \"Silent Oil\" <me>",
            },
            Label                   = "Silent Oil",
            Image                   = "ITEM:4165",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:4"] = {
            ActionType              = 'Spell',
            Id                      = 353,
            Macro                   = T{
                "/ma \"Tonko: Ichi\" <me>",
            },
            Label                   = "Tonko: Ichi",
            Image                   = "spells/353.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:6"] = {
            ActionType              = 'Spell',
            Id                      = 320,
            Macro                   = T{
                "/ma \"Katon: Ichi\" <t>",
            },
            Label                   = "Katon: Ichi",
            Image                   = "spells/320.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:3"] = {
            ActionType              = 'Ability',
            Id                      = 583,
            Macro                   = T{
                "/ja \"Leave\" <me>",
            },
            Label                   = "Leave",
            Image                   = "abilities/71.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:8"] = {
            ActionType              = 'Weaponskill',
            Id                      = 130,
            Macro                   = T{
                "/ws \"Blade: Teki\" <t>",
            },
            Label                   = "Blade: Teki",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:5"] = {
            ActionType              = 'Spell',
            Id                      = 329,
            Macro                   = T{
                "/ma \"Doton: Ichi\" <t>",
            },
            Label                   = "Doton: Ichi",
            Image                   = "spells/329.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:7"] = {
            ActionType              = 'Spell',
            Id                      = 335,
            Macro                   = T{
                "/ma \"Suiton: Ichi\" <t>",
            },
            Label                   = "Suiton: Ichi",
            Image                   = "spells/335.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:5"] = {
            ActionType              = 'Weaponskill',
            Id                      = 131,
            Macro                   = T{
                "/ws \"Blade: To\" <t>",
            },
            Label                   = "Blade: To",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:5"] = {
            ActionType              = 'Spell',
            Id                      = 354,
            Macro                   = T{
                "/ma \"Tonko: Ni\" <me>",
            },
            Label                   = "Tonko: Ni",
            Image                   = "spells/354.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:4"] = {
            ActionType              = 'Weaponskill',
            Id                      = 134,
            Macro                   = T{
                "/ws \"Blade: Jin\" <t>",
            },
            Label                   = "Blade: Jin",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:6"] = {
            ActionType              = 'Spell',
            Id                      = 348,
            Macro                   = T{
                "/ma \"Kurayami: Ni\" <t>",
            },
            Label                   = "Kurayami: Ni",
            Image                   = "spells/348.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:8"] = {
            ActionType              = 'Spell',
            Id                      = 341,
            Macro                   = T{
                "/ma \"Jubaku: Ichi\" <t>",
            },
            Label                   = "Jubaku: Ichi",
            Image                   = "spells/341.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:2"] = {
            ActionType              = 'Ability',
            Id                      = 544,
            Macro                   = T{
                "/ja \"Warcry\" <me>",
            },
            Label                   = "Warcry",
            Image                   = "abilities/32.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:7"] = {
            ActionType              = 'Spell',
            Id                      = 345,
            Macro                   = T{
                "/ma \"Hojo: Ni\" <t>",
            },
            Label                   = "Hojo: Ni",
            Image                   = "spells/345.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:1"] = {
            ActionType              = 'Command',
            Macro                   = T{
                "/ra <t>",
            },
            Label                   = "RA",
            Image                   = "spells/1014.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:3"] = {
            ActionType              = 'Weaponskill',
            Id                      = 136,
            Macro                   = T{
                "/ws \"Blade: Ku\" <t>",
            },
            Label                   = "Blade: Ku",
            Image                   = "ITEM:21922",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:6"] = {
            ActionType              = 'Weaponskill',
            Id                      = 128,
            Macro                   = T{
                "/ws \"Blade: Rin\" <t>",
            },
            Label                   = "Blade: Rin",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:8"] = {
            ActionType              = 'Spell',
            Id                      = 332,
            Macro                   = T{
                "/ma \"Raiton: Ichi\" <t>",
            },
            Label                   = "Raiton: Ichi",
            Image                   = "spells/332.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:4"] = {
            ActionType              = 'Ability',
            Id                      = 564,
            Macro                   = T{
                "/ja \"Charm\" <t>",
            },
            Label                   = "Charm",
            Image                   = "abilities/52.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:5"] = {
            ActionType              = 'Ability',
            Id                      = 547,
            Macro                   = T{
                "/ja \"Provoke\" <stnpc>",
            },
            Label                   = "Provoke",
            Image                   = "abilities/35.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:2"] = {
            ActionType              = 'Spell',
            Id                      = 326,
            Macro                   = T{
                "/ma \"Huton: Ichi\" <t>",
            },
            Label                   = "Huton: Ichi",
            Image                   = "spells/326.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:5"] = {
            ActionType              = 'Ability',
            Id                      = 584,
            Macro                   = T{
                "/ja \"Sic\" <me>",
            },
            Label                   = "Sic",
            Image                   = "abilities/72.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:3"] = {
            ActionType              = 'Spell',
            Id                      = 339,
            Macro                   = T{
                "/ma \"Utsusemi: Ni\" <me>",
            },
            Label                   = "Utsusemi: Ni",
            Image                   = "spells/339.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:2"] = {
            ActionType              = 'Weaponskill',
            Id                      = 132,
            Macro                   = T{
                "/ws \"Blade: Chi\" <t>",
            },
            Label                   = "Blade: Chi",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:4"] = {
            ActionType              = 'Ability',
            Id                      = 760,
            Macro                   = T{
                "/ja \"Yonin\" <me>",
            },
            Label                   = "Yonin",
            Image                   = "abilities/248.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:7"] = {
            ActionType              = 'Weaponskill',
            Id                      = 129,
            Macro                   = T{
                "/ws \"Blade: Retsu\" <t>",
            },
            Label                   = "Blade: Retsu",
            Image                   = "ITEM:17793",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:4"] = {
            ActionType              = 'Ability',
            Id                      = 545,
            Macro                   = T{
                "/ja \"Defender\" <me>",
            },
            Label                   = "Defender",
            Image                   = "abilities/33.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:4"] = {
            ActionType              = 'Ability',
            Id                      = 543,
            Macro                   = T{
                "/ja \"Berserk\" <me>",
            },
            Label                   = "Berserk",
            Image                   = "abilities/31.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:1"] = {
            ActionType              = 'Spell',
            Id                      = 338,
            Macro                   = T{
                "/ma \"Utsusemi: Ichi\" <me>",
            },
            Label                   = "Utsusemi: Ichi",
            Image                   = "spells/338.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 335,
                Macro                   = T{
                    "/ma \"Suiton: Ichi\" <t>",
                },
                Label                   = "Suiton: Ichi",
                Image                   = "spells/335.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Spell',
                Id                      = 350,
                Macro                   = T{
                    "/ma \"Dokumori: Ichi\" <t>",
                },
                Label                   = "Dokumori: Ichi",
                Image                   = "spells/350.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Spell',
                Id                      = 323,
                Macro                   = T{
                    "/ma \"Hyoton: Ichi\" <t>",
                },
                Label                   = "Hyoton: Ichi",
                Image                   = "spells/323.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:5"] = {
                ActionType              = 'Spell',
                Id                      = 354,
                Macro                   = T{
                    "/ma \"Tonko: Ni\" <me>",
                },
                Label                   = "Tonko: Ni",
                Image                   = "spells/354.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 320,
                Macro                   = T{
                    "/ma \"Katon: Ichi\" <t>",
                },
                Label                   = "Katon: Ichi",
                Image                   = "spells/320.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 332,
                Macro                   = T{
                    "/ma \"Raiton: Ichi\" <t>",
                },
                Label                   = "Raiton: Ichi",
                Image                   = "spells/332.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Spell',
                Id                      = 326,
                Macro                   = T{
                    "/ma \"Huton: Ichi\" <t>",
                },
                Label                   = "Huton: Ichi",
                Image                   = "spells/326.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:3"] = {
                ActionType              = 'Spell',
                Id                      = 339,
                Macro                   = T{
                    "/ma \"Utsusemi: Ni\" <me>",
                },
                Label                   = "Utsusemi: Ni",
                Image                   = "spells/339.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:6"] = {
                ActionType              = 'Spell',
                Id                      = 230,
                Macro                   = T{
                    "/ma \"Bio\" <t>",
                },
                Label                   = "Bio",
                Image                   = "spells/230.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 347,
                Macro                   = T{
                    "/ma \"Kurayami: Ichi\" <t>",
                },
                Label                   = "Kurayami: Ichi",
                Image                   = "spells/347.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:1"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells/338.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 543,
                Macro                   = T{
                    "/ja \"Berserk\" <me>",
                },
                Label                   = "Berserk",
                Image                   = "abilities/31.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 344,
                Macro                   = T{
                    "/ma \"Hojo: Ichi\" <t>",
                },
                Label                   = "Hojo: Ichi",
                Image                   = "spells/344.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 329,
                Macro                   = T{
                    "/ma \"Doton: Ichi\" <t>",
                },
                Label                   = "Doton: Ichi",
                Image                   = "spells/329.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Ni", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 336,
                Macro                   = T{
                    "/ma \"Suiton: Ni\" <t>",
                },
                Label                   = "Suiton: Ni",
                Image                   = "spells/336.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Spell',
                Id                      = 324,
                Macro                   = T{
                    "/ma \"Hyoton: Ni\" <t>",
                },
                Label                   = "Hyoton: Ni",
                Image                   = "spells/324.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 321,
                Macro                   = T{
                    "/ma \"Katon: Ni\" <t>",
                },
                Label                   = "Katon: Ni",
                Image                   = "spells/321.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 333,
                Macro                   = T{
                    "/ma \"Raiton: Ni\" <t>",
                },
                Label                   = "Raiton: Ni",
                Image                   = "spells/333.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Spell',
                Id                      = 327,
                Macro                   = T{
                    "/ma \"Huton: Ni\" <t>",
                },
                Label                   = "Huton: Ni",
                Image                   = "spells/327.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:7"] = {
                ActionType              = 'Ability',
                Id                      = 582,
                Macro                   = T{
                    "/ja \"Heel\" <me>",
                },
                Label                   = "Heel",
                Image                   = "abilities/70.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:8"] = {
                ActionType              = 'Ability',
                Id                      = 585,
                Macro                   = T{
                    "/ja \"Stay\" <me>",
                },
                Label                   = "Stay",
                Image                   = "abilities/73.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Ability',
                Id                      = 584,
                Macro                   = T{
                    "/ja \"Sic\" <me>",
                },
                Label                   = "Sic",
                Image                   = "abilities/72.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:4"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities/52.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:6"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities/69.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 330,
                Macro                   = T{
                    "/ma \"Doton: Ni\" <t>",
                },
                Label                   = "Doton: Ni",
                Image                   = "spells/330.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};