return T{
    Default = T{
        ["LT:7"] = {
            ActionType              = 'Spell',
            Id                      = 29,
            Macro                   = T{
                "/ma \"Banish II\" <stnpc>",
            },
            Label                   = "Banish II",
            Image                   = "spells/29.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:1"] = {
            ActionType              = 'Spell',
            Id                      = 112,
            Macro                   = T{
                "/ma \"Flash\" <stnpc>",
            },
            Label                   = "Flash",
            Image                   = "spells/112.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:3"] = {
            ActionType              = 'Ability',
            Id                      = 545,
            Macro                   = T{
                "/ja \"Defender\" <me>",
            },
            Label                   = "Defender",
            Image                   = "abilities/33.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:8"] = {
            ActionType              = 'Ability',
            Id                      = 534,
            Macro                   = T{
                "/mdt",
            },
            Label                   = "MDT",
            Image                   = "abilities/1hr.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:5"] = {
            ActionType              = 'Ability',
            Id                      = 670,
            Macro                   = T{
                "/dps",
            },
            Label                   = "DPS",
            Image                   = "abilities/158.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:5"] = {
            ActionType              = 'Ability',
            Id                      = 547,
            Macro                   = T{
                "/ja \"Provoke\" <stnpc>",
            },
            Label                   = "Provoke",
            Image                   = "abilities/35.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:6"] = {
            ActionType              = 'Spell',
            Id                      = 46,
            Macro                   = T{
                "/ma \"Protect IV\" <t>",
            },
            Label                   = "Protect IV",
            Image                   = "spells/46.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:5"] = {
            ActionType              = 'Spell',
            Id                      = 4,
            Macro                   = T{
                "/ma \"Cure IV\" <stpc>",
            },
            Label                   = "Cure IV",
            Image                   = "spells/4.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:4"] = {
            ActionType              = 'Ability',
            Id                      = 591,
            Macro                   = T{
                "/ja \"Cover\" <stpc>",
            },
            Label                   = "Cover",
            Image                   = "abilities/79.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:4"] = {
            ActionType              = 'Ability',
            Id                      = 560,
            Macro                   = T{
                "/ja \"Sentinel\" <me>",
            },
            Label                   = "Sentinel",
            Image                   = "abilities/48.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:6"] = {
            ActionType              = 'Ability',
            Id                      = 564,
            Macro                   = T{
                "/ja \"Charm\" <t>",
            },
            Label                   = "Charm",
            Image                   = "abilities/52.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:6"] = {
            ActionType              = 'Spell',
            Id                      = 1,
            Macro                   = T{
                "/ma \"Cure\" <stpc>",
            },
            Label                   = "Cure",
            Image                   = "spells/1.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:1"] = {
            ActionType              = 'Spell',
            Id                      = 338,
            Macro                   = T{
                "/ma \"Utsusemi: Ichi\" <me>",
            },
            Label                   = "Utsusemi: Ichi",
            Image                   = "spells/338.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:2"] = {
            ActionType              = 'Ability',
            Id                      = 604,
            Macro                   = T{
                "/ja \"Rampart\" <me>",
            },
            Label                   = "Rampart",
            Image                   = "abilities/92.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:7"] = {
            ActionType              = 'Spell',
            Id                      = 2,
            Macro                   = T{
                "/ma \"Cure II\" <stpc>",
            },
            Label                   = "Cure II",
            Image                   = "spells/2.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:1"] = {
            ActionType              = 'Ability',
            Id                      = 558,
            Macro                   = T{
                "/ja \"Shield Bash\" <stnpc>",
            },
            Label                   = "Shield Bash",
            Image                   = "abilities/46.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:3"] = {
            ActionType              = 'Ability',
            Id                      = 670,
            Macro                   = T{
                "/ja \"Chivalry\" <me>",
            },
            Label                   = "Chivalry",
            Image                   = "abilities/158.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:4"] = {
            ActionType              = 'Ability',
            Id                      = 585,
            Macro                   = T{
                "/ja \"Stay\" <me>",
            },
            Label                   = "Stay",
            Image                   = "abilities/73.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:2"] = {
            ActionType              = 'Spell',
            Id                      = 310,
            Macro                   = T{
                "/ma \"Enlight\" <me>",
            },
            Label                   = "Enlight",
            Image                   = "spells/310.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:1"] = {
            ActionType              = 'Ability',
            Id                      = 581,
            Macro                   = T{
                "/ja \"Fight\" <t>",
            },
            Label                   = "Fight",
            Image                   = "abilities/69.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:1"] = {
            ActionType              = 'Spell',
            Id                      = 12,
            Macro                   = T{
                "/ma \"Raise\" <t>",
            },
            Label                   = "Raise",
            Image                   = "spells/12.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:6"] = {
            ActionType              = 'Spell',
            Id                      = 28,
            Macro                   = T{
                "/ma \"Banish\" <stnpc>",
            },
            Label                   = "Banish",
            Image                   = "spells/28.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:6"] = {
            ActionType              = 'Ability',
            Id                      = 534,
            Macro                   = T{
                "/pdt",
            },
            Label                   = "PDT",
            Image                   = "abilities/1hr.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:3"] = {
            ActionType              = 'Ability',
            Id                      = 582,
            Macro                   = T{
                "/ja \"Heel\" <me>",
            },
            Label                   = "Heel",
            Image                   = "abilities/70.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:7"] = {
            ActionType              = 'Spell',
            Id                      = 50,
            Macro                   = T{
                "/ma \"Shell III\" <t>",
            },
            Label                   = "Shell III",
            Image                   = "spells/50.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:3"] = {
            ActionType              = 'Spell',
            Id                      = 339,
            Macro                   = T{
                "/ma \"Utsusemi: Ni\" <me>",
            },
            Label                   = "Utsusemi: Ni",
            Image                   = "spells/339.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:8"] = {
            ActionType              = 'Spell',
            Id                      = 3,
            Macro                   = T{
                "/ma \"Cure III\" <stpc>",
            },
            Label                   = "Cure III",
            Image                   = "spells/3.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:5"] = {
            ActionType              = 'Ability',
            Id                      = 584,
            Macro                   = T{
                "/ja \"Sic\" <me>",
            },
            Label                   = "Sic",
            Image                   = "abilities/72.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:5"] = {
            ActionType              = 'Spell',
            Id                      = 45,
            Macro                   = T{
                "/ma \"Protect III\" <t>",
            },
            Label                   = "Protect III",
            Image                   = "spells/45.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:8"] = {
            ActionType              = 'Spell',
            Id                      = 21,
            Macro                   = T{
                "/ma \"Holy\" <stnpc>",
            },
            Label                   = "Holy",
            Image                   = "spells/21.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:8"] = {
            ActionType              = 'Spell',
            Id                      = 49,
            Macro                   = T{
                "/ma \"Shell II\" <t>",
            },
            Label                   = "Shell II",
            Image                   = "spells/49.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:7"] = {
            ActionType              = 'Ability',
            Id                      = 583,
            Macro                   = T{
                "/ja \"Leave\" <me>",
            },
            Label                   = "Leave",
            Image                   = "abilities/71.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["LT:1"] = {
                ActionType              = 'Spell',
                Id                      = 112,
                Macro                   = T{
                    "/ma \"Flash\" <stnpc>",
                },
                Label                   = "Flash",
                Image                   = "spells/112.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Ability',
                Id                      = 545,
                Macro                   = T{
                    "/ja \"Defender\" <me>",
                },
                Label                   = "Defender",
                Image                   = "abilities/33.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 165,
                Macro                   = T{
                    "/ws \"Skullbreaker\" <t>",
                },
                Label                   = "Skullbreaker",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 46,
                Macro                   = T{
                    "/ma \"Protect IV\" <t>",
                },
                Label                   = "Protect IV",
                Image                   = "spells/46.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 167,
                Macro                   = T{
                    "/ws \"Judgment\" <t>",
                },
                Label                   = "Judgment",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:4"] = {
                ActionType              = 'Ability',
                Id                      = 585,
                Macro                   = T{
                    "/ja \"Stay\" <me>",
                },
                Label                   = "Stay",
                Image                   = "abilities/73.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 28,
                Macro                   = T{
                    "/ma \"Banish\" <stnpc>",
                },
                Label                   = "Banish",
                Image                   = "spells/28.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:3"] = {
                ActionType              = 'Ability',
                Id                      = 559,
                Macro                   = T{
                    "/ja \"Holy Circle\" <me>",
                },
                Label                   = "Holy Circle",
                Image                   = "abilities/47.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 162,
                Macro                   = T{
                    "/ws \"Brainshaker\" <t>",
                },
                Label                   = "Brainshaker",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Ability',
                Id                      = 547,
                Macro                   = T{
                    "/ja \"Provoke\" <stnpc>",
                },
                Label                   = "Provoke",
                Image                   = "abilities/35.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 29,
                Macro                   = T{
                    "/ma \"Banish II\" <stnpc>",
                },
                Label                   = "Banish II",
                Image                   = "spells/29.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 161,
                Macro                   = T{
                    "/ws \"Seraph Strike\" <t>",
                },
                Label                   = "Seraph Strike",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Weaponskill',
                Id                      = 166,
                Macro                   = T{
                    "/ws \"True Strike\" <t>",
                },
                Label                   = "True Strike",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Spell',
                Id                      = 3,
                Macro                   = T{
                    "/ma \"Cure III\" <stpc>",
                },
                Label                   = "Cure III",
                Image                   = "spells/3.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 4,
                Macro                   = T{
                    "/ma \"Cure IV\" <stpc>",
                },
                Label                   = "Cure IV",
                Image                   = "spells/4.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 1,
                Macro                   = T{
                    "/ma \"Cure\" <stpc>",
                },
                Label                   = "Cure",
                Image                   = "spells/1.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:1"] = {
                ActionType              = 'Spell',
                Id                      = 338,
                Macro                   = T{
                    "/ma \"Utsusemi: Ichi\" <me>",
                },
                Label                   = "Utsusemi: Ichi",
                Image                   = "spells/338.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 604,
                Macro                   = T{
                    "/ja \"Rampart\" <me>",
                },
                Label                   = "Rampart",
                Image                   = "abilities/92.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 560,
                Macro                   = T{
                    "/ja \"Sentinel\" <me>",
                },
                Label                   = "Sentinel",
                Image                   = "abilities/48.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 558,
                Macro                   = T{
                    "/ja \"Shield Bash\" <stnpc>",
                },
                Label                   = "Shield Bash",
                Image                   = "abilities/46.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 670,
                Macro                   = T{
                    "/ja \"Chivalry\" <me>",
                },
                Label                   = "Chivalry",
                Image                   = "abilities/158.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Ability',
                Id                      = 591,
                Macro                   = T{
                    "/ja \"Cover\" <stpc>",
                },
                Label                   = "Cover",
                Image                   = "abilities/79.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 160,
                Macro                   = T{
                    "/ws \"Shining Strike\" <t>",
                },
                Label                   = "Shining Strike",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:1"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities/69.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 163,
                Macro                   = T{
                    "/ws \"Starlight\" <me>",
                },
                Label                   = "Starlight",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:6"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities/52.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:6"] = {
                ActionType              = 'Ability',
                Id                      = 534,
                Macro                   = T{
                    "/pdt",
                },
                Label                   = "PDT",
                Image                   = "abilities/1hr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:3"] = {
                ActionType              = 'Ability',
                Id                      = 582,
                Macro                   = T{
                    "/ja \"Heel\" <me>",
                },
                Label                   = "Heel",
                Image                   = "abilities/70.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:7"] = {
                ActionType              = 'Ability',
                Id                      = 583,
                Macro                   = T{
                    "/ja \"Leave\" <me>",
                },
                Label                   = "Leave",
                Image                   = "abilities/71.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 2,
                Macro                   = T{
                    "/ma \"Cure II\" <stpc>",
                },
                Label                   = "Cure II",
                Image                   = "spells/2.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 164,
                Macro                   = T{
                    "/ws \"Moonlight\" <me>",
                },
                Label                   = "Moonlight",
                Image                   = "ITEM:17440",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:5"] = {
                ActionType              = 'Ability',
                Id                      = 584,
                Macro                   = T{
                    "/ja \"Sic\" <me>",
                },
                Label                   = "Sic",
                Image                   = "abilities/72.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 45,
                Macro                   = T{
                    "/ma \"Protect III\" <t>",
                },
                Label                   = "Protect III",
                Image                   = "spells/45.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Spell',
                Id                      = 310,
                Macro                   = T{
                    "/ma \"Enlight\" <me>",
                },
                Label                   = "Enlight",
                Image                   = "spells/310.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:8"] = {
                ActionType              = 'Ability',
                Id                      = 534,
                Macro                   = T{
                    "/mdt",
                },
                Label                   = "MDT",
                Image                   = "abilities/1hr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 21,
                Macro                   = T{
                    "/ma \"Holy\" <stnpc>",
                },
                Label                   = "Holy",
                Image                   = "spells/21.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Sword", Bindings = T{
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 32,
                Macro                   = T{
                    "/ws \"Fast Blade\" <t>",
                },
                Label                   = "Fast Blade",
                Image                   = "ITEM:16555",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 35,
                Macro                   = T{
                    "/ws \"Flat Blade\" <t>",
                },
                Label                   = "Flat Blade",
                Image                   = "ITEM:16555",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 37,
                Macro                   = T{
                    "/ws \"Seraph Blade\" <t>",
                },
                Label                   = "Seraph Blade",
                Image                   = "ITEM:16555",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Weaponskill',
                Id                      = 42,
                Macro                   = T{
                    "/ws \"Savage Blade\" <t>",
                },
                Label                   = "Savage Blade",
                Image                   = "ITEM:21621",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 39,
                Macro                   = T{
                    "/ws \"Spirits Within\" <t>",
                },
                Label                   = "Spirits Within",
                Image                   = "ITEM:16555",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 41,
                Macro                   = T{
                    "/ws \"Swift Blade\" <t>",
                },
                Label                   = "Swift Blade",
                Image                   = "ITEM:16555",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 33,
                Macro                   = T{
                    "/ws \"Burning Blade\" <t>",
                },
                Label                   = "Burning Blade",
                Image                   = "ITEM:16555",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 40,
                Macro                   = T{
                    "/ws \"Vorpal Blade\" <t>",
                },
                Label                   = "Vorpal Blade",
                Image                   = "ITEM:16555",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:5"] = {
                ActionType              = 'Ability',
                Id                      = 670,
                Macro                   = T{
                    "/dps",
                },
                Label                   = "DPS",
                Image                   = "abilities/158.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};