return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["LT:4"] = {
                ActionType              = 'Spell',
                Id                      = 378,
                Macro                   = T{
                    "/ma \"Army's Paeon\" <me>",
                },
                Label                   = "Army's Paeon",
                Image                   = "spells/378.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Spell',
                Id                      = 389,
                Macro                   = T{
                    "/ma \"Knight's Minne\" <me>",
                },
                Label                   = "Knight's Minne",
                Image                   = "spells/389.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 208,
                Macro                   = T{
                    "/ws \"Hot Shot\" <t>",
                },
                Label                   = "Hot Shot",
                Image                   = "ITEM:17244",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ra <t>",
                },
                Label                   = "Attack",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 16,
                Macro                   = T{
                    "/ws \"Wasp Sting\" <t>",
                },
                Label                   = "Wasp Sting",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 220,
                Macro                   = T{
                    "/ma \"Poison\" <t>",
                },
                Label                   = "Poison",
                Image                   = "spells/220.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 571,
                Macro                   = T{
                    "/ja \"Sharpshot\" <me>",
                },
                Label                   = "Sharpshot",
                Image                   = "abilities/59.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Spell',
                Id                      = 394,
                Macro                   = T{
                    "/ma \"Valor Minuet\" <me>",
                },
                Label                   = "Valor Minuet",
                Image                   = "spells/394.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};