return T{
    Default = T{
        ["RT2:7"] = {
            ActionType              = 'Spell',
            Id                      = 2,
            Macro                   = T{
                "/ma \"Cure II\" <t>",
            },
            Label                   = "Cure II",
            Image                   = "spells/2.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:4"] = {
            ActionType              = 'Spell',
            Id                      = 16,
            Macro                   = T{
                "/ma \"Blindna\" <t>",
            },
            Label                   = "Blindna",
            Image                   = "spells/16.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:5"] = {
            ActionType              = 'Spell',
            Id                      = 137,
            Macro                   = T{
                "/ma \"Sneak\" <t>",
            },
            Label                   = "Sneak",
            Image                   = "spells/137.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:3"] = {
            ActionType              = 'Item',
            Id                      = 4520,
            Macro                   = T{
                "/item \"Coin Cookie\" <me>",
            },
            Label                   = "Coin Cookie",
            Image                   = "ITEM:4520",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:6"] = {
            ActionType              = 'Spell',
            Id                      = 1,
            Macro                   = T{
                "/ma \"Cure\" <t>",
            },
            Label                   = "Cure",
            Image                   = "spells/1.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:1"] = {
            ActionType              = 'Command',
            Macro                   = T{
                "/target <bt>",
            },
            Label                   = "BT",
            Image                   = "misc/command.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:8"] = {
            ActionType              = 'Spell',
            Id                      = 3,
            Macro                   = T{
                "/ma \"Cure III\" <t>",
            },
            Label                   = "Cure III",
            Image                   = "spells/3.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:1"] = {
            ActionType              = 'Ability',
            Id                      = 542,
            Macro                   = T{
                "/ja \"Astral Flow\" <me>",
            },
            Label                   = "Astral Flow",
            Image                   = "abilities/1hr.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:7"] = {
            ActionType              = 'Ability',
            Id                      = 601,
            Macro                   = T{
                "/ja \"Retreat\" <me>",
            },
            Label                   = "Retreat",
            Image                   = "abilities/89.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:2"] = {
            ActionType              = 'Spell',
            Id                      = 14,
            Macro                   = T{
                "/ma \"Poisona\" <t>",
            },
            Label                   = "Poisona",
            Image                   = "spells/14.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:6"] = {
            ActionType              = 'Spell',
            Id                      = 53,
            Macro                   = T{
                "/ma \"Blink\" <me>",
            },
            Label                   = "Blink",
            Image                   = "spells/53.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT:6"] = {
            ActionType              = 'Ability',
            Id                      = 600,
            Macro                   = T{
                "/ja \"Assault\" <t>",
            },
            Label                   = "Assault",
            Image                   = "abilities/88.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:1"] = {
            ActionType              = 'Spell',
            Id                      = 17,
            Macro                   = T{
                "/ma \"Silena\" <t>",
            },
            Label                   = "Silena",
            Image                   = "spells/17.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:6"] = {
            ActionType              = 'Spell',
            Id                      = 44,
            Macro                   = T{
                "/ma \"Protect II\" <t>",
            },
            Label                   = "Protect II",
            Image                   = "spells/44.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:6"] = {
            ActionType              = 'Spell',
            Id                      = 12,
            Macro                   = T{
                "/ma \"Raise\" <t>",
            },
            Label                   = "Raise",
            Image                   = "spells/12.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT:4"] = {
            ActionType              = 'Ability',
            Id                      = 602,
            Macro                   = T{
                "/ja \"Release\" <me>",
                "/tc palette change Base",
            },
            Label                   = "Release",
            Image                   = "abilities/90.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:5"] = {
            ActionType              = 'Spell',
            Id                      = 108,
            Macro                   = T{
                "/ma \"Regen\" <t>",
            },
            Label                   = "Regen",
            Image                   = "spells/108.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:8"] = {
            ActionType              = 'Spell',
            Id                      = 131,
            Macro                   = T{
                "/ma \"Shellra II\" <me>",
            },
            Label                   = "Shellra II",
            Image                   = "spells/131.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RT2:3"] = {
            ActionType              = 'Spell',
            Id                      = 15,
            Macro                   = T{
                "/ma \"Paralyna\" <t>",
            },
            Label                   = "Paralyna",
            Image                   = "spells/15.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:5"] = {
            ActionType              = 'Spell',
            Id                      = 49,
            Macro                   = T{
                "/ma \"Shell II\" <t>",
            },
            Label                   = "Shell II",
            Image                   = "spells/49.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:7"] = {
            ActionType              = 'Spell',
            Id                      = 54,
            Macro                   = T{
                "/ma \"Stoneskin\" <me>",
            },
            Label                   = "Stoneskin",
            Image                   = "spells/54.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:3"] = {
            ActionType              = 'Spell',
            Id                      = 135,
            Macro                   = T{
                "/ma \"Reraise\" <me>",
            },
            Label                   = "Reraise",
            Image                   = "spells/135.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["RTLT:8"] = {
            ActionType              = 'Spell',
            Id                      = 136,
            Macro                   = T{
                "/ma \"Invisible\" <t>",
            },
            Label                   = "Invisible",
            Image                   = "spells/136.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:7"] = {
            ActionType              = 'Spell',
            Id                      = 126,
            Macro                   = T{
                "/ma \"Protectra II\" <me>",
            },
            Label                   = "Protectra II",
            Image                   = "spells/126.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Spell',
                Id                      = 303,
                Macro                   = T{
                    "/ma \"Ramuh\" <me>",
                    "/tc palette change Ramuh",
                },
                Label                   = "Ramuh",
                Image                   = "spells/303.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:4"] = {
                ActionType              = 'Spell',
                Id                      = 16,
                Macro                   = T{
                    "/ma \"Blindna\" <t>",
                },
                Label                   = "Blindna",
                Image                   = "spells/16.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Spell',
                Id                      = 137,
                Macro                   = T{
                    "/ma \"Sneak\" <t>",
                },
                Label                   = "Sneak",
                Image                   = "spells/137.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Spell',
                Id                      = 300,
                Macro                   = T{
                    "/ma \"Leviathan\" <me>",
                    "/tc palette change Leviathan",
                },
                Label                   = "Leviathan",
                Image                   = "spells/300.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Spell',
                Id                      = 304,
                Macro                   = T{
                    "/ma \"Diabolos\" <me>",
                    "/tc palette change Diabolos",
                },
                Label                   = "Diabolos",
                Image                   = "spells/304.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 1,
                Macro                   = T{
                    "/ma \"Cure\" <t>",
                },
                Label                   = "Cure",
                Image                   = "spells/1.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Spell',
                Id                      = 296,
                Macro                   = T{
                    "/ma \"Carbuncle\" <me>",
                    "/tc palette change Carbuncle",
                },
                Label                   = "Carbuncle",
                Image                   = "spells/296.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 3,
                Macro                   = T{
                    "/ma \"Cure III\" <t>",
                },
                Label                   = "Cure III",
                Image                   = "spells/3.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Spell',
                Id                      = 301,
                Macro                   = T{
                    "/ma \"Garuda\" <me>",
                    "/tc palette change Garuda",
                },
                Label                   = "Garuda",
                Image                   = "spells/301.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Spell',
                Id                      = 299,
                Macro                   = T{
                    "/ma \"Titan\" <me>",
                    "/tc palette change Titan",
                },
                Label                   = "Titan",
                Image                   = "spells/299.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Spell',
                Id                      = 298,
                Macro                   = T{
                    "/ma \"Ifrit\" <me>",
                    "/tc palette change Ifrit",
                },
                Label                   = "Ifrit",
                Image                   = "spells/298.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:7"] = {
                ActionType              = 'Spell',
                Id                      = 126,
                Macro                   = T{
                    "/ma \"Protectra II\" <me>",
                },
                Label                   = "Protectra II",
                Image                   = "spells/126.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Spell',
                Id                      = 297,
                Macro                   = T{
                    "/ma \"Fenrir\" <me>",
                    "/tc palette change Fenrir",
                },
                Label                   = "Fenrir",
                Image                   = "spells/297.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 44,
                Macro                   = T{
                    "/ma \"Protect II\" <t>",
                },
                Label                   = "Protect II",
                Image                   = "spells/44.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:6"] = {
                ActionType              = 'Spell',
                Id                      = 53,
                Macro                   = T{
                    "/ma \"Blink\" <me>",
                },
                Label                   = "Blink",
                Image                   = "spells/53.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:7"] = {
                ActionType              = 'Spell',
                Id                      = 2,
                Macro                   = T{
                    "/ma \"Cure II\" <t>",
                },
                Label                   = "Cure II",
                Image                   = "spells/2.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:1"] = {
                ActionType              = 'Spell',
                Id                      = 17,
                Macro                   = T{
                    "/ma \"Silena\" <t>",
                },
                Label                   = "Silena",
                Image                   = "spells/17.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Spell',
                Id                      = 302,
                Macro                   = T{
                    "/ma \"Shiva\" <me>",
                    "/tc palette change Shiva",
                },
                Label                   = "Shiva",
                Image                   = "spells/302.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:6"] = {
                ActionType              = 'Spell',
                Id                      = 12,
                Macro                   = T{
                    "/ma \"Raise\" <t>",
                },
                Label                   = "Raise",
                Image                   = "spells/12.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:3"] = {
                ActionType              = 'Spell',
                Id                      = 15,
                Macro                   = T{
                    "/ma \"Paralyna\" <t>",
                },
                Label                   = "Paralyna",
                Image                   = "spells/15.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:8"] = {
                ActionType              = 'Spell',
                Id                      = 131,
                Macro                   = T{
                    "/ma \"Shellra II\" <me>",
                },
                Label                   = "Shellra II",
                Image                   = "spells/131.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:3"] = {
                ActionType              = 'Spell',
                Id                      = 135,
                Macro                   = T{
                    "/ma \"Reraise\" <me>",
                },
                Label                   = "Reraise",
                Image                   = "spells/135.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 49,
                Macro                   = T{
                    "/ma \"Shell II\" <t>",
                },
                Label                   = "Shell II",
                Image                   = "spells/49.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Spell',
                Id                      = 108,
                Macro                   = T{
                    "/ma \"Regen\" <t>",
                },
                Label                   = "Regen",
                Image                   = "spells/108.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Spell',
                Id                      = 136,
                Macro                   = T{
                    "/ma \"Invisible\" <t>",
                },
                Label                   = "Invisible",
                Image                   = "spells/136.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:2"] = {
                ActionType              = 'Spell',
                Id                      = 14,
                Macro                   = T{
                    "/ma \"Poisona\" <t>",
                },
                Label                   = "Poisona",
                Image                   = "spells/14.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Carbuncle", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 1026,
                Macro                   = T{
                    "/ja \"Shining Ruby\" <me>",
                },
                Label                   = "Shining Ruby",
                Image                   = "abilities/514.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1030,
                Macro                   = T{
                    "/ja \"Searing Light\" <t>",
                },
                Label                   = "Searing Light",
                Image                   = "abilities/518.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1024,
                Macro                   = T{
                    "/ja \"Healing Ruby\" <t>",
                },
                Label                   = "Healing Ruby",
                Image                   = "abilities/512.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1029,
                Macro                   = T{
                    "/ja \"Healing Ruby II\" <me>",
                },
                Label                   = "Healing Ruby II",
                Image                   = "abilities/517.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1027,
                Macro                   = T{
                    "/ja \"Glittering Ruby\" <me>",
                },
                Label                   = "Glittering Ruby",
                Image                   = "abilities/515.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Ability',
                Id                      = 600,
                Macro                   = T{
                    "/ja \"Assault\" <t>",
                },
                Label                   = "Assault",
                Image                   = "abilities/88.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1025,
                Macro                   = T{
                    "/ja \"Poison Nails\" <t>",
                },
                Label                   = "Poison Nails",
                Image                   = "abilities/513.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1028,
                Macro                   = T{
                    "/ja \"Meteorite\" <t>",
                },
                Label                   = "Meteorite",
                Image                   = "abilities/516.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Ability',
                Id                      = 601,
                Macro                   = T{
                    "/ja \"Retreat\" <me>",
                },
                Label                   = "Retreat",
                Image                   = "abilities/89.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Spell',
                Id                      = 23,
                Macro                   = T{
                    "/ma \"Dia\" <t>",
                },
                Label                   = "Dia",
                Image                   = "spells/23.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Ifrit", Bindings = T{
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 1059,
                Macro                   = T{
                    "/ja \"Double Punch\" <t>",
                },
                Label                   = "Double Punch",
                Image                   = "abilities/547.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1064,
                Macro                   = T{
                    "/ja \"Inferno\" <t>",
                },
                Label                   = "Inferno",
                Image                   = "abilities/552.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 1058,
                Macro                   = T{
                    "/ja \"Burning Strike\" <t>",
                },
                Label                   = "Burning Strike",
                Image                   = "abilities/546.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1060,
                Macro                   = T{
                    "/ja \"Crimson Howl\" <me>",
                },
                Label                   = "Crimson Howl",
                Image                   = "abilities/548.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1057,
                Macro                   = T{
                    "/ja \"Fire II\" <t>",
                },
                Label                   = "Fire II",
                Image                   = "abilities/545.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1056,
                Macro                   = T{
                    "/ja \"Punch\" <t>",
                },
                Label                   = "Punch",
                Image                   = "abilities/544.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 1061,
                Macro                   = T{
                    "/ja \"Fire IV\" <t>",
                },
                Label                   = "Fire IV",
                Image                   = "abilities/549.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1062,
                Macro                   = T{
                    "/ja \"Flaming Crush\" <t>",
                },
                Label                   = "Flaming Crush",
                Image                   = "abilities/550.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Titan", Bindings = T{
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 1075,
                Macro                   = T{
                    "/ja \"Megalith Throw\" <t>",
                },
                Label                   = "Megalith Throw",
                Image                   = "abilities/563.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1080,
                Macro                   = T{
                    "/ja \"Earthen Fury\" <t>",
                },
                Label                   = "Earthen Fury",
                Image                   = "abilities/568.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1072,
                Macro                   = T{
                    "/ja \"Rock Throw\" <t>",
                },
                Label                   = "Rock Throw",
                Image                   = "abilities/560.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 1074,
                Macro                   = T{
                    "/ja \"Rock Buster\" <t>",
                },
                Label                   = "Rock Buster",
                Image                   = "abilities/562.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1073,
                Macro                   = T{
                    "/ja \"Stone II\" <t>",
                },
                Label                   = "Stone II",
                Image                   = "abilities/561.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1076,
                Macro                   = T{
                    "/ja \"Earthen Ward\" <me>",
                },
                Label                   = "Earthen Ward",
                Image                   = "abilities/564.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 1077,
                Macro                   = T{
                    "/ja \"Stone IV\" <t>",
                },
                Label                   = "Stone IV",
                Image                   = "abilities/565.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1078,
                Macro                   = T{
                    "/ja \"Mountain Buster\" <t>",
                },
                Label                   = "Mountain Buster",
                Image                   = "abilities/566.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Garuda", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 1106,
                Macro                   = T{
                    "/ja \"Whispering Wind\" <me>",
                },
                Label                   = "Whispering Wind",
                Image                   = "abilities/594.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1112,
                Macro                   = T{
                    "/ja \"Aerial Blast\" <t>",
                },
                Label                   = "Aerial Blast",
                Image                   = "abilities/600.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1108,
                Macro                   = T{
                    "/ja \"Aerial Armor\" <me>",
                },
                Label                   = "Aerial Armor",
                Image                   = "abilities/596.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 1109,
                Macro                   = T{
                    "/ja \"Aero IV\" <t>",
                },
                Label                   = "Aero IV",
                Image                   = "abilities/597.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1105,
                Macro                   = T{
                    "/ja \"Aero II\" <t>",
                },
                Label                   = "Aero II",
                Image                   = "abilities/593.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1104,
                Macro                   = T{
                    "/ja \"Claw\" <t>",
                },
                Label                   = "Claw",
                Image                   = "abilities/592.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1107,
                Macro                   = T{
                    "/ja \"Hastega\" <me>",
                },
                Label                   = "Hastega",
                Image                   = "abilities/595.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1110,
                Macro                   = T{
                    "/ja \"Predator Claws\" <t>",
                },
                Label                   = "Predator Claws",
                Image                   = "abilities/598.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Fenrir", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 1043,
                Macro                   = T{
                    "/ja \"Lunar Roar\" <t>",
                },
                Label                   = "Lunar Roar",
                Image                   = "abilities/531.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1048,
                Macro                   = T{
                    "/ja \"Howling Moon\" <t>",
                },
                Label                   = "Howling Moon",
                Image                   = "abilities/536.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1046,
                Macro                   = T{
                    "/ja \"Eclipse Bite\" <t>",
                },
                Label                   = "Eclipse Bite",
                Image                   = "abilities/534.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1042,
                Macro                   = T{
                    "/ja \"Lunar Cry\" <t>",
                },
                Label                   = "Lunar Cry",
                Image                   = "abilities/530.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1041,
                Macro                   = T{
                    "/ja \"Crescent Fang\" <t>",
                },
                Label                   = "Crescent Fang",
                Image                   = "abilities/529.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1040,
                Macro                   = T{
                    "/ja \"Moonlit Charge\" <t>",
                },
                Label                   = "Moonlit Charge",
                Image                   = "abilities/528.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1045,
                Macro                   = T{
                    "/ja \"Ecliptic Howl\" <me>",
                },
                Label                   = "Ecliptic Howl",
                Image                   = "abilities/533.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1044,
                Macro                   = T{
                    "/ja \"Ecliptic Growl\" <me>",
                },
                Label                   = "Ecliptic Growl",
                Image                   = "abilities/532.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Shiva", Bindings = T{
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 1125,
                Macro                   = T{
                    "/ja \"Blizzard IV\" <t>",
                },
                Label                   = "Blizzard IV",
                Image                   = "abilities/613.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1128,
                Macro                   = T{
                    "/ja \"Diamond Dust\" <t>",
                },
                Label                   = "Diamond Dust",
                Image                   = "abilities/616.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1122,
                Macro                   = T{
                    "/ja \"Frost Armor\" <me>",
                },
                Label                   = "Frost Armor",
                Image                   = "abilities/610.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 1123,
                Macro                   = T{
                    "/ja \"Sleepga\" <t>",
                },
                Label                   = "Sleepga",
                Image                   = "abilities/611.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 1124,
                Macro                   = T{
                    "/ja \"Double Slap\" <t>",
                },
                Label                   = "Double Slap",
                Image                   = "abilities/612.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1121,
                Macro                   = T{
                    "/ja \"Blizzard II\" <t>",
                },
                Label                   = "Blizzard II",
                Image                   = "abilities/609.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1120,
                Macro                   = T{
                    "/ja \"Axe Kick\" <t>",
                    "/party Axe Kick <call21>",
                },
                Label                   = "Axe Kick",
                Image                   = "abilities/608.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 1120,
                Macro                   = T{
                    "/ja \"Axe Kick\" <t>",
                },
                Label                   = "Axe Kick",
                Image                   = "abilities/608.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1126,
                Macro                   = T{
                    "/ja \"Rush\" <t>",
                },
                Label                   = "Rush",
                Image                   = "abilities/614.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Ramuh", Bindings = T{
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 1141,
                Macro                   = T{
                    "/ja \"Thunder IV\" <t>",
                },
                Label                   = "Thunder IV",
                Image                   = "abilities/629.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1144,
                Macro                   = T{
                    "/ja \"Judgment Bolt\" <t>",
                },
                Label                   = "Judgment Bolt",
                Image                   = "abilities/632.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 1140,
                Macro                   = T{
                    "/ja \"Lightning Armor\" <me>",
                },
                Label                   = "Lightning Armor",
                Image                   = "abilities/628.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1138,
                Macro                   = T{
                    "/ja \"Rolling Thunder\" <me>",
                },
                Label                   = "Rolling Thunder",
                Image                   = "abilities/626.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1137,
                Macro                   = T{
                    "/ja \"Thunder II\" <t>",
                },
                Label                   = "Thunder II",
                Image                   = "abilities/625.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 1139,
                Macro                   = T{
                    "/ja \"Thunderspark\" <t>",
                },
                Label                   = "Thunderspark",
                Image                   = "abilities/627.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1136,
                Macro                   = T{
                    "/ja \"Shock Strike\" <t>",
                },
                Label                   = "Shock Strike",
                Image                   = "abilities/624.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1142,
                Macro                   = T{
                    "/ja \"Chaotic Strike\" <t>",
                },
                Label                   = "Chaotic Strike",
                Image                   = "abilities/630.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Diabolos", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 1170,
                Macro                   = T{
                    "/ja \"Nightmare\" <t>",
                },
                Label                   = "Nightmare",
                Image                   = "abilities/658.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1176,
                Macro                   = T{
                    "/ja \"Ruinous Omen\" <t>",
                },
                Label                   = "Ruinous Omen",
                Image                   = "abilities/664.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1169,
                Macro                   = T{
                    "/ja \"Somnolence\" <t>",
                },
                Label                   = "Somnolence",
                Image                   = "abilities/657.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 1173,
                Macro                   = T{
                    "/ja \"Dream Shroud\" <me>",
                },
                Label                   = "Dream Shroud",
                Image                   = "abilities/661.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1168,
                Macro                   = T{
                    "/ja \"Camisado\" <t>",
                },
                Label                   = "Camisado",
                Image                   = "abilities/656.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1174,
                Macro                   = T{
                    "/ja \"Nether Blast\" <t>",
                },
                Label                   = "Nether Blast",
                Image                   = "abilities/662.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1171,
                Macro                   = T{
                    "/ja \"Ultimate Terror\" <t>",
                },
                Label                   = "Ultimate Terror",
                Image                   = "abilities/659.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1172,
                Macro                   = T{
                    "/ja \"Noctoshield\" <me>",
                },
                Label                   = "Noctoshield",
                Image                   = "abilities/660.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
        { Name="Leviathan", Bindings = T{
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 1093,
                Macro                   = T{
                    "/ja \"Water IV\" <t>",
                },
                Label                   = "Water IV",
                Image                   = "abilities/581.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1096,
                Macro                   = T{
                    "/ja \"Tidal Wave\" <t>",
                },
                Label                   = "Tidal Wave",
                Image                   = "abilities/584.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 1091,
                Macro                   = T{
                    "/ja \"Spring Water\" <me>",
                },
                Label                   = "Spring Water",
                Image                   = "abilities/579.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 1090,
                Macro                   = T{
                    "/ja \"Tail Whip\" <t>",
                },
                Label                   = "Tail Whip",
                Image                   = "abilities/578.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Ability',
                Id                      = 1089,
                Macro                   = T{
                    "/ja \"Water II\" <t>",
                },
                Label                   = "Water II",
                Image                   = "abilities/577.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 1092,
                Macro                   = T{
                    "/ja \"Slowga\" <t>",
                },
                Label                   = "Slowga",
                Image                   = "abilities/580.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Ability',
                Id                      = 1088,
                Macro                   = T{
                    "/ja \"Barracuda Dive\" <t>",
                },
                Label                   = "Barracuda Dive",
                Image                   = "abilities/576.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 1094,
                Macro                   = T{
                    "/ja \"Spinning Dive\" <t>",
                },
                Label                   = "Spinning Dive",
                Image                   = "abilities/582.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};