return T{
    Default = T{
        ["LTRT:8"] = {
            ActionType              = 'Ability',
            Id                      = 533,
            Macro                   = T{
                "/pdt",
            },
            Label                   = "PDT",
            Image                   = "abilities/1hr.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:5"] = {
            ActionType              = 'Spell',
            Id                      = 353,
            Macro                   = T{
                "/ma \"Tonko: Ichi\" <me>",
            },
            Label                   = "Tonko: Ichi",
            Image                   = "spells/353.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:6"] = {
            ActionType              = 'Spell',
            Id                      = 273,
            Macro                   = T{
                "/ma \"Sleepga\" <t>",
            },
            Label                   = "Sleepga",
            Image                   = "spells/273.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LTRT:1"] = {
            ActionType              = 'Spell',
            Id                      = 338,
            Macro                   = T{
                "/ma \"Utsusemi: Ichi\" <me>",
            },
            Label                   = "Utsusemi: Ichi",
            Image                   = "spells/338.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
        ["LT2:7"] = {
            ActionType              = 'Spell',
            Id                      = 189,
            Macro                   = T{
                "/ma \"Stonega\" <t>",
            },
            Label                   = "Stonega",
            Image                   = "spells/189.png",
            ShowCost                = true,
            ShowCross               = true,
            ShowFade                = true,
            ShowRecast              = true,
            ShowName                = true,
            ShowTrigger             = true,
            ShowSkillchainIcon      = true,
            ShowSkillchainAnimation = true,
            ShowHotkey              = false,
        },
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["RT2:7"] = {
                ActionType              = 'Ability',
                Id                      = 583,
                Macro                   = T{
                    "/ja \"Leave\" <me>",
                },
                Label                   = "Leave",
                Image                   = "abilities/71.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ra <t>",
                    "/p ! Pulling <t> !",
                },
                Label                   = "Pull",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Ability',
                Id                      = 556,
                Macro                   = T{
                    "/ja \"Sneak Attack\" <me>",
                },
                Label                   = "Sneak Attack",
                Image                   = "abilities/44.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Weaponskill',
                Id                      = 21,
                Macro                   = T{
                    "/ws \"Energy Steal\" <t>",
                },
                Label                   = "Energy Steal",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Ability',
                Id                      = 833,
                Macro                   = T{
                    "/ja \"Bully\" <t>",
                },
                Label                   = "Bully",
                Image                   = "abilities/321.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:1"] = {
                ActionType              = 'Weaponskill',
                Id                      = 23,
                Macro                   = T{
                    "/ws \"Dancing Edge\" <t>",
                },
                Label                   = "Dancing Edge",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:4"] = {
                ActionType              = 'Ability',
                Id                      = 575,
                Macro                   = T{
                    "/ja \"Meditate\" <me>",
                },
                Label                   = "Meditate",
                Image                   = "abilities/63.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 25,
                Macro                   = T{
                    "/ws \"Evisceration\" <t>",
                },
                Label                   = "Evisceration",
                Image                   = "ITEM:21565",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:3"] = {
                ActionType              = 'Ability',
                Id                      = 585,
                Macro                   = T{
                    "/ja \"Stay\" <me>",
                },
                Label                   = "Stay",
                Image                   = "abilities/73.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 18,
                Macro                   = T{
                    "/ws \"Shadowstitch\" <t>",
                },
                Label                   = "Shadowstitch",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:2"] = {
                ActionType              = 'Ability',
                Id                      = 533,
                Macro                   = T{
                    "/mdt",
                },
                Label                   = "MDT",
                Image                   = "abilities/1hr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 24,
                Macro                   = T{
                    "/ws \"Shark Bite\" <t>",
                },
                Label                   = "Shark Bite",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Weaponskill',
                Id                      = 17,
                Macro                   = T{
                    "/ws \"Viper Bite\" <t>",
                },
                Label                   = "Viper Bite",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:5"] = {
                ActionType              = 'Spell',
                Id                      = 353,
                Macro                   = T{
                    "/ma \"Tonko: Ichi\" <me>",
                },
                Label                   = "Tonko: Ichi",
                Image                   = "spells/353.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Weaponskill',
                Id                      = 22,
                Macro                   = T{
                    "/ws \"Energy Drain\" <t>",
                },
                Label                   = "Energy Drain",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/ra <t>",
                },
                Label                   = "RA",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:7"] = {
                ActionType              = 'Ability',
                Id                      = 554,
                Macro                   = T{
                    "/ja \"Flee\" <me>",
                },
                Label                   = "Flee",
                Image                   = "abilities/42.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Ability',
                Id                      = 557,
                Macro                   = T{
                    "/ja \"Mug\" <t>",
                },
                Label                   = "Mug",
                Image                   = "abilities/45.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 19,
                Macro                   = T{
                    "/ws \"Gust Slash\" <t>",
                },
                Label                   = "Gust Slash",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/assist Lojan",
                },
                Label                   = "Lojan",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/equip Ammo \"Bloody Bolt\"",
                    "/ra <t>",
                },
                Label                   = "Blood",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/equip Ammo \"Sleep Bolt\"",
                    "/ra <t>",
                },
                Label                   = "Sleep",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/equip Ammo \"Blind Bolt\"",
                    "/ra <t>",
                },
                Label                   = "Blind",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Ability',
                Id                      = 748,
                Macro                   = T{
                    "/ja \"Collaborator\" <stpc>",
                },
                Label                   = "Collaborator",
                Image                   = "abilities/236.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Ability',
                Id                      = 596,
                Macro                   = T{
                    "/ja \"Accomplice\" <stpc>",
                },
                Label                   = "Accomplice",
                Image                   = "abilities/84.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:2"] = {
                ActionType              = 'Ability',
                Id                      = 582,
                Macro                   = T{
                    "/ja \"Heel\" <me>",
                },
                Label                   = "Heel",
                Image                   = "abilities/70.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 16,
                Macro                   = T{
                    "/ws \"Wasp Sting\" <t>",
                },
                Label                   = "Wasp Sting",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:8"] = {
                ActionType              = 'Ability',
                Id                      = 533,
                Macro                   = T{
                    "/pdt",
                },
                Label                   = "PDT",
                Image                   = "abilities/1hr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:1"] = {
                ActionType              = 'Ability',
                Id                      = 581,
                Macro                   = T{
                    "/ja \"Fight\" <t>",
                },
                Label                   = "Fight",
                Image                   = "abilities/69.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:6"] = {
                ActionType              = 'Spell',
                Id                      = 273,
                Macro                   = T{
                    "/ma \"Sleepga\" <t>",
                },
                Label                   = "Sleepga",
                Image                   = "spells/273.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 25,
                Macro                   = T{
                    "/th",
                },
                Label                   = "TH",
                Image                   = "ITEM:21565",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Ability',
                Id                      = 588,
                Macro                   = T{
                    "/ja \"Trick Attack\" <me>",
                },
                Label                   = "Trick Attack",
                Image                   = "abilities/76.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:4"] = {
                ActionType              = 'Ability',
                Id                      = 533,
                Macro                   = T{
                    "/eva",
                },
                Label                   = "EVASION",
                Image                   = "abilities/1hr.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:3"] = {
                ActionType              = 'Spell',
                Id                      = 339,
                Macro                   = T{
                    "/ma \"Utsusemi: Ni\" <me>",
                },
                Label                   = "Utsusemi: Ni",
                Image                   = "spells/339.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Weaponskill',
                Id                      = 20,
                Macro                   = T{
                    "/ws \"Cyclone\" <t>",
                },
                Label                   = "Cyclone",
                Image                   = "ITEM:18020",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:4"] = {
                ActionType              = 'Ability',
                Id                      = 584,
                Macro                   = T{
                    "/ja \"Sic\" <me>",
                },
                Label                   = "Sic",
                Image                   = "abilities/72.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT2:5"] = {
                ActionType              = 'Ability',
                Id                      = 564,
                Macro                   = T{
                    "/ja \"Charm\" <t>",
                },
                Label                   = "Charm",
                Image                   = "abilities/52.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Ability',
                Id                      = 555,
                Macro                   = T{
                    "/ja \"Hide\" <me>",
                },
                Label                   = "Hide",
                Image                   = "abilities/43.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT2:1"] = {
                ActionType              = 'Ability',
                Id                      = 574,
                Macro                   = T{
                    "/ja \"Third Eye\" <me>",
                },
                Label                   = "Third Eye",
                Image                   = "abilities/62.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Ability',
                Id                      = 553,
                Macro                   = T{
                    "/ja \"Steal\" <t>",
                },
                Label                   = "Steal",
                Image                   = "abilities/41.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};